from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    615304: Achievement(
        id=615304,
        title="""trophy_campaign_gold""",
        description="""Earn a gold trophy in any campaign mission""",
        points=1,
        badge="00000",
    ),
    615305: Achievement(
        id=615305,
        title="""trophy_challenge_gold""",
        description="""Earn a gold trophy in any challenge mission""",
        points=1,
        badge="00000",
    ),
    615306: Achievement(
        id=615306,
        title="""trophy_shotgun_gold""",
        description="""Earn the gold trophy in all 3 Shotgun Challenges""",
        points=10,
        badge="00000",
    ),
    615307: Achievement(
        id=615307,
        title="""trophy_sheep_gold""",
        description="""Earn the gold trophy in all 3 Super Sheep Challenges""",
        points=10,
        badge="00000",
    ),
    615308: Achievement(
        id=615308,
        title="""trophy_jetpack_gold""",
        description="""Earn the gold trophy in all 3 Jetpack Challenges""",
        points=10,
        badge="00000",
    ),
    615309: Achievement(
        id=615309,
        title="""trophy_parachute_gold""",
        description="""Earn the gold trophy in all 3 Parachute Challenges""",
        points=10,
        badge="00000",
    ),
    615310: Achievement(
        id=615310,
        title="""trophy_deathmatch_gold""",
        description="""Earn the gold trophy in all 10 Deathmatch Challenges""",
        points=25,
        badge="00000",
    ),
    612940: Achievement(
        id=612940,
        title="""Worms School""",
        description="""Complete all 5 tutorial missions and unlock The Driving Range""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612941: Achievement(
        id=612941,
        title="""The Battle for Wormandy""",
        description="""Complete the first campaign mission, D-Day""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612942: Achievement(
        id=612942,
        title="""Fixing the Ice Dispenser""",
        description="""Complete the 5th campaign mission, Ice, Ice, Maybe""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612943: Achievement(
        id=612943,
        title="""Hurry Skurry""",
        description="""Complete the 10th campaign mission, Helter Skelter""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612944: Achievement(
        id=612944,
        title="""mission_15""",
        description="""Complete the 15th campaign mission, Crop Circle""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612945: Achievement(
        id=612945,
        title="""mission_20""",
        description="""Complete the 20th campaign mission, High Stakes""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612946: Achievement(
        id=612946,
        title="""mission_25""",
        description="""Complete the 25th campaign mission, Plaice Holder""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612947: Achievement(
        id=612947,
        title="""mission_30""",
        description="""Complete the 30th campaign mission, Beautiful Balloon""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612948: Achievement(
        id=612948,
        title="""mission_35""",
        description="""Complete the 35th and last campaign mission, Alien Juice Suckers""",
        points=25,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    614494: Achievement(
        id=614494,
        title="""secret_atlantis""",
        description="""Discover the secret of Atlantis Training Facility""",
        points=1,
        badge="00000",
    ),
    614495: Achievement(
        id=614495,
        title="""secret_grave""",
        description="""Discover the secret of Grave Digger""",
        points=1,
        badge="00000",
    ),
    614496: Achievement(
        id=614496,
        title="""secret_schools""",
        description="""Discover the secret of Schools In For Summer""",
        points=2,
        badge="00000",
    ),
    614497: Achievement(
        id=614497,
        title="""secret_quick_fix""",
        description="""Discover the secret of A Quick Fix""",
        points=2,
        badge="00000",
    ),
    614498: Achievement(
        id=614498,
        title="""secret_showdown""",
        description="""Discover the secret of Showdown at the OK Corale Reef""",
        points=1,
        badge="00000",
    ),
    614499: Achievement(
        id=614499,
        title="""secret_funfair""",
        description="""Discover the secret of Nobody Rides For Free""",
        points=3,
        badge="00000",
    ),
    614500: Achievement(
        id=614500,
        title="""secret_breakfast""",
        description="""Discover the secret of Beefcake Breakfast Brawl""",
        points=1,
        badge="00000",
    ),
    610362: Achievement(
        id=610362,
        title="""Bovine Artillery""",
        description="""Unlock the Mad Cow""",
        points=5,
        badge="00000",
    ),
    610366: Achievement(
        id=610366,
        title="""When Sheeps Fly""",
        description="""Unlock the Super Sheep""",
        points=5,
        badge="00000",
    ),
    610364: Achievement(
        id=610364,
        title="""Ancient Ritual""",
        description="""Unlock the Earthquake""",
        points=5,
        badge="00000",
    ),
    610363: Achievement(
        id=610363,
        title="""The Soft Fruit of Doom""",
        description="""Unlock the Banana Bomb""",
        points=5,
        badge="00000",
    ),
    610365: Achievement(
        id=610365,
        title="""The Nuclear Test""",
        description="""Unlock the Nuclear Bomb""",
        points=10,
        badge="00000",
    ),
    610358: Achievement(
        id=610358,
        title="""Options!""",
        description="""Unlock all 5 unlockable gameplay schemes""",
        points=10,
        badge="00000",
    ),
    610359: Achievement(
        id=610359,
        title="""Super Villain""",
        description="""Unlock all 5 unlockable worm voices""",
        points=10,
        badge="00000",
    ),
    610360: Achievement(
        id=610360,
        title="""The Art of War""",
        description="""Unlock all 18 unlockable Wormapedia entries""",
        points=25,
        badge="00000",
    ),
    610361: Achievement(
        id=610361,
        title="""Globe Trotter""",
        description="""Unlock all 29 unlockable multiplayer landscapes""",
        points=50,
        badge="00000",
    ),
    610367: Achievement(
        id=610367,
        title="""Let's Go Gambling!""",
        description="""Spin the Wormpot slots machine""",
        points=1,
        badge="00000",
    ),
    612677: Achievement(
        id=612677,
        title="""Hole in One""",
        description="""Destroy every target at least once in The Driving Range""",
        points=2,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    163325: Leaderboard(
        id=163325,
        title="""Gold Trophy Time Tracker""",
        description="""Hold L1 and R1 for 3 seconds in the main menu to activate or deactivate the time tracker for gold trophies""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163408: Leaderboard(
        id=163408,
        title="""Shotgun Challenge 1""",
        description="""Score the highest time in the Shotgun Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163409: Leaderboard(
        id=163409,
        title="""Shotgun Challenge 2""",
        description="""Score the highest time in the Shotgun Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163410: Leaderboard(
        id=163410,
        title="""Shotgun Challenge 3""",
        description="""Score the highest time in the Shotgun Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163411: Leaderboard(
        id=163411,
        title="""Super Sheep Challenge 1""",
        description="""Score the highest time in the Super Sheep Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163412: Leaderboard(
        id=163412,
        title="""Super Sheep Challenge 2""",
        description="""Score the highest time in the Super Sheep Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163413: Leaderboard(
        id=163413,
        title="""Super Sheep Challenge 3""",
        description="""Score the highest time in the Super Sheep Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163414: Leaderboard(
        id=163414,
        title="""Jetpack Challenge 1""",
        description="""Score the highest time in the Jetpack Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163415: Leaderboard(
        id=163415,
        title="""Jetpack Challenge 2""",
        description="""Score the highest time in the Jetpack Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163416: Leaderboard(
        id=163416,
        title="""Jetpack Challenge 3""",
        description="""Score the highest time in the Jetpack Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163417: Leaderboard(
        id=163417,
        title="""Parachute Challenge 1""",
        description="""Score the highest time in the Parachute Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163418: Leaderboard(
        id=163418,
        title="""Parachute Challenge 2""",
        description="""Score the highest time in the Parachute Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163419: Leaderboard(
        id=163419,
        title="""Parachute Challenge 3""",
        description="""Score the highest time in the Parachute Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163420: Leaderboard(
        id=163420,
        title="""Deathmatch Challenge 1""",
        description="""Score the lowest time in the Deathmatch Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163421: Leaderboard(
        id=163421,
        title="""Deathmatch Challenge 2""",
        description="""Score the lowest time in the Deathmatch Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163422: Leaderboard(
        id=163422,
        title="""Deathmatch Challenge 3""",
        description="""Score the lowest time in the Deathmatch Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163423: Leaderboard(
        id=163423,
        title="""Deathmatch Challenge 4""",
        description="""Score the lowest time in the Deathmatch Challenge 4""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163424: Leaderboard(
        id=163424,
        title="""Deathmatch Challenge 5""",
        description="""Score the lowest time in the Deathmatch Challenge 5""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163425: Leaderboard(
        id=163425,
        title="""Deathmatch Challenge 6""",
        description="""Score the lowest time in the Deathmatch Challenge 6""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163426: Leaderboard(
        id=163426,
        title="""Deathmatch Challenge 7""",
        description="""Score the lowest time in the Deathmatch Challenge 7""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163427: Leaderboard(
        id=163427,
        title="""Deathmatch Challenge 8""",
        description="""Score the lowest time in the Deathmatch Challenge 8""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163428: Leaderboard(
        id=163428,
        title="""Deathmatch Challenge 9""",
        description="""Score the lowest time in the Deathmatch Challenge 9""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163429: Leaderboard(
        id=163429,
        title="""Deathmatch Challenge 10""",
        description="""Score the lowest time in the Deathmatch Challenge 10""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163430: Leaderboard(
        id=163430,
        title="""Time Trial - Rum Deal""",
        description="""Complete Rum Deal as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163431: Leaderboard(
        id=163431,
        title="""Time Trial - Take My Cherry""",
        description="""Complete Take My Cherry as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163432: Leaderboard(
        id=163432,
        title="""Time Trial - Falling For You""",
        description="""Complete Falling For You as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163433: Leaderboard(
        id=163433,
        title="""Time Trial - Worm and the Beanstalk""",
        description="""Complete Worm and the Beanstalk as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163434: Leaderboard(
        id=163434,
        title="""Time Trial - Trial of the Damned""",
        description="""Complete Trial of the Damned as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163435: Leaderboard(
        id=163435,
        title="""Time Trial - Plaice Holder""",
        description="""Complete Plaice Holder as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163436: Leaderboard(
        id=163436,
        title="""Time Trial - To Boldly Go""",
        description="""Complete To Boldly Go as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163437: Leaderboard(
        id=163437,
        title="""Time Trial - A Good Nights Sleep""",
        description="""Complete A Good Nights Sleep as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163438: Leaderboard(
        id=163438,
        title="""Time Trial - Costa Del Danger""",
        description="""Complete Costa Del Danger as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
})