from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    612940: Achievement(
        id=612940,
        title="""Worms School""",
        description="""Complete all 5 tutorial missions and unlock The Driving Range""",
        points=5,
        badge="00000",
    ),
    612941: Achievement(
        id=612941,
        title="""The Battle for Wormandy""",
        description="""Complete the first campaign mission, D-Day""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612942: Achievement(
        id=612942,
        title="""Fixing the Ice Dispenser""",
        description="""Complete the 5th campaign mission, Ice, Ice, Maybe""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612943: Achievement(
        id=612943,
        title="""Hurry Skurry""",
        description="""Complete the 10th campaign mission, Helter Skelter""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612944: Achievement(
        id=612944,
        title="""UFO Catcher""",
        description="""Complete the 15th campaign mission, Crop Circle""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612945: Achievement(
        id=612945,
        title="""The Prince of Darkness""",
        description="""Complete the 20th campaign mission, High Stakes""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612946: Achievement(
        id=612946,
        title="""Escape Room""",
        description="""Complete the 25th campaign mission, Plaice Holder""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612947: Achievement(
        id=612947,
        title="""Let's Zepple In""",
        description="""Complete the 30th campaign mission, Beautiful Balloon""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612948: Achievement(
        id=612948,
        title="""Woooarrrgh""",
        description="""Complete the 35th and last campaign mission, Alien Juice Suckers""",
        points=25,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    614494: Achievement(
        id=614494,
        title="""Secret of Atlantis""",
        description="""Discover the secret of Atlantis Training Facility""",
        points=1,
        badge="00000",
    ),
    614495: Achievement(
        id=614495,
        title="""Secret of the Graveyard""",
        description="""Discover the secret of Grave Digger""",
        points=1,
        badge="00000",
    ),
    614496: Achievement(
        id=614496,
        title="""Secret of the School""",
        description="""Discover the secret of Schools In For Summer""",
        points=2,
        badge="00000",
    ),
    614497: Achievement(
        id=614497,
        title="""Secret of the Keyboard""",
        description="""Discover the secret of A Quick Fix""",
        points=2,
        badge="00000",
    ),
    614498: Achievement(
        id=614498,
        title="""Secret of the Reef""",
        description="""Discover the secret of Showdown at the OK Corale Reef""",
        points=1,
        badge="00000",
    ),
    614499: Achievement(
        id=614499,
        title="""Secret of the Funfair""",
        description="""Discover the secret of Nobody Rides For Free""",
        points=3,
        badge="00000",
    ),
    614500: Achievement(
        id=614500,
        title="""Secret of the House""",
        description="""Discover the secret of Beefcake Breakfast Brawl""",
        points=1,
        badge="00000",
    ),
    610362: Achievement(
        id=610362,
        title="""Bovine Artillery""",
        description="""Unlock the Mad Cow""",
        points=5,
        badge="00000",
    ),
    610366: Achievement(
        id=610366,
        title="""When Sheeps Fly""",
        description="""Unlock the Super Sheep""",
        points=5,
        badge="00000",
    ),
    610364: Achievement(
        id=610364,
        title="""Ancient Ritual""",
        description="""Unlock the Earthquake""",
        points=5,
        badge="00000",
    ),
    610363: Achievement(
        id=610363,
        title="""The Soft Fruit of Doom""",
        description="""Unlock the Banana Bomb""",
        points=5,
        badge="00000",
    ),
    610365: Achievement(
        id=610365,
        title="""The Nuclear Test""",
        description="""Unlock the Nuclear Bomb""",
        points=10,
        badge="00000",
    ),
    610358: Achievement(
        id=610358,
        title="""Options!""",
        description="""Unlock all 5 unlockable gameplay schemes""",
        points=10,
        badge="00000",
    ),
    610359: Achievement(
        id=610359,
        title="""Super Villain""",
        description="""Unlock all 5 unlockable worm voices""",
        points=10,
        badge="00000",
    ),
    610360: Achievement(
        id=610360,
        title="""The Art of War""",
        description="""Unlock all 18 unlockable Wormapedia entries""",
        points=25,
        badge="00000",
    ),
    610361: Achievement(
        id=610361,
        title="""Globe Trotter""",
        description="""Unlock all 29 unlockable multiplayer landscapes""",
        points=25,
        badge="00000",
    ),
    615304: Achievement(
        id=615304,
        title="""Medal of Honor""",
        description="""Earn a gold trophy in any campaign mission""",
        points=1,
        badge="00000",
    ),
    615305: Achievement(
        id=615305,
        title="""Gold Challenger""",
        description="""Earn a gold trophy in any challenge mission""",
        points=1,
        badge="00000",
    ),
    615306: Achievement(
        id=615306,
        title="""Shotgun Master""",
        description="""Earn the gold trophy in all 3 Shotgun Challenges""",
        points=10,
        badge="00000",
    ),
    615307: Achievement(
        id=615307,
        title="""Super Sheep Master""",
        description="""Earn the gold trophy in all 3 Super Sheep Challenges""",
        points=10,
        badge="00000",
    ),
    615308: Achievement(
        id=615308,
        title="""Jetpack Master""",
        description="""Earn the gold trophy in all 3 Jetpack Challenges""",
        points=10,
        badge="00000",
    ),
    615309: Achievement(
        id=615309,
        title="""Parachute Master""",
        description="""Earn the gold trophy in all 3 Parachute Challenges""",
        points=10,
        badge="00000",
    ),
    615310: Achievement(
        id=615310,
        title="""Deathmatch Master""",
        description="""Earn the gold trophy in all 10 Deathmatch Challenges""",
        points=50,
        badge="00000",
    ),
    610367: Achievement(
        id=610367,
        title="""Let's Go Gambling!""",
        description="""Spin the Wormpot slots machine""",
        points=1,
        badge="00000",
    ),
    615956: Achievement(
        id=615956,
        title="""Kamikaze""",
        description="""Kill a CPU enemy worm after your own worm's death""",
        points=3,
        badge="00000",
    ),
    615951: Achievement(
        id=615951,
        title="""The Worminator""",
        description="""Kill 3 or more CPU enemy worms in one turn""",
        points=5,
        badge="00000",
    ),
    612677: Achievement(
        id=612677,
        title="""Hole in One""",
        description="""Destroy every target at least once in The Driving Range""",
        points=2,
        badge="00000",
    ),
    615536: Achievement(
        id=615536,
        title="""Rewriting History""",
        description="""Earn the gold trophy in D-Day without using the jetpack""",
        points=5,
        badge="00000",
    ),
    615537: Achievement(
        id=615537,
        title="""Corny Situation""",
        description="""Earn the gold trophy in Crate Britain after killing all the enemy worms""",
        points=5,
        badge="00000",
    ),
    615546: Achievement(
        id=615546,
        title="""Grave Digger""",
        description="""Earn the gold trophy in Grave Danger after collecting all the crates""",
        points=3,
        badge="00000",
    ),
    615547: Achievement(
        id=615547,
        title="""Water-Way to Go""",
        description="""Earn the gold trophy in A Leek in a Vegetable Patch without any of your worms drowning""",
        points=5,
        badge="00000",
    ),
    615548: Achievement(
        id=615548,
        title="""No Time to Chill""",
        description="""Earn the gold trophy in Ice, Ice, Maybe in no more than 2 player turns""",
        points=5,
        badge="00000",
    ),
    615549: Achievement(
        id=615549,
        title="""Pushing Them Back to the Grave""",
        description="""Earn the gold trophy in When Annelids Collide only using melee attacks""",
        points=5,
        badge="00000",
    ),
    615550: Achievement(
        id=615550,
        title="""Grog from the Seas""",
        description="""Earn the gold trophy in Rum Deal in a single turn without destroying any crate""",
        points=3,
        badge="00000",
    ),
    615551: Achievement(
        id=615551,
        title="""Windmiller's Quality""",
        description="""Kill all enemy worms before collecting any health crate and earn the gold trophy in Earn Your Crust""",
        points=3,
        badge="00000",
    ),
    615552: Achievement(
        id=615552,
        title="""Bad Apple""",
        description="""Earn the gold trophy in Apple Core Island without using the jetpack""",
        points=5,
        badge="00000",
    ),
    615553: Achievement(
        id=615553,
        title="""Grenadier""",
        description="""Earn the gold trophy in Helter Skelter without using the bazooka""",
        points=25,
        badge="00000",
    ),
    615554: Achievement(
        id=615554,
        title="""Cherry Go Round""",
        description="""Earn the gold trophy in Take My Cherry with more than 6:00 left on the round timer""",
        points=5,
        badge="00000",
    ),
    615555: Achievement(
        id=615555,
        title="""Clean-up King""",
        description="""Earn the gold trophy in In Space, No-One Can Hear You Clean without using the jetpack more than once and without using grenades, cluster bombs or the bazooka""",
        points=10,
        badge="00000",
    ),
    615556: Achievement(
        id=615556,
        title="""Washed Up""",
        description="""Earn the gold trophy in Shiver Me Timbers before the start of the Captain's second turn without using the Girder""",
        points=10,
        badge="00000",
    ),
    615557: Achievement(
        id=615557,
        title="""Bail Out, Bail Out""",
        description="""Reach the weapon crate in Falling For You in a single turn""",
        points=10,
        badge="00000",
    ),
    615558: Achievement(
        id=615558,
        title="""Bobby BlastOff""",
        description="""Earn the gold trophy in Crop Circle without collecting any crate""",
        points=5,
        badge="00000",
    ),
    615689: Achievement(
        id=615689,
        title="""Tree Climber""",
        description="""Earn the gold trophy in Tree Village Trouble without using movement utilities""",
        points=5,
        badge="00000",
    ),
    615690: Achievement(
        id=615690,
        title="""Jack of All Trades""",
        description="""Earn the gold trophy in Movie Mayhem without using each weapon more than once""",
        points=5,
        badge="00000",
    ),
    615919: Achievement(
        id=615919,
        title="""Fee Fi Fo Fum""",
        description="""Reach the safety boat with any of your worm without using the parachute in Worm and the Beanstalk""",
        points=5,
        badge="00000",
    ),
    615920: Achievement(
        id=615920,
        title="""Bringing Back Bullying""",
        description="""Earn the gold trophy in School's in for Summer without any of your worms dying""",
        points=5,
        badge="00000",
    ),
    615921: Achievement(
        id=615921,
        title="""Evil Stays Asleep""",
        description="""Earn the gold trophy in High Stakes without awakening any undead worm""",
        points=5,
        badge="00000",
    ),
    615922: Achievement(
        id=615922,
        title="""Short Circuit""",
        description="""Earn the gold trophy in A Quick Fix without killing any enemy or placing more than 6 landmines""",
        points=5,
        badge="00000",
    ),
    615923: Achievement(
        id=615923,
        title="""Chickening Out""",
        description="""Earn the gold trophy in All Cooped Up without using any explosive weapon""",
        points=5,
        badge="00000",
    ),
    615924: Achievement(
        id=615924,
        title="""Parkour of the Damned""",
        description="""Earn the gold trophy in Trial of the Damned without triggering more than 1 island explosion""",
        points=10,
        badge="00000",
    ),
    615925: Achievement(
        id=615925,
        title="""Avast Ye Matey!""",
        description="""Earn the gold trophy in Showdown at the OK Corale Reef in no more than 5 player turns""",
        points=10,
        badge="00000",
    ),
    615926: Achievement(
        id=615926,
        title="""Puzzling Shortcut""",
        description="""Earn the gold trophy in Plaice Holder without using any low gravity""",
        points=5,
        badge="00000",
    ),
    615927: Achievement(
        id=615927,
        title="""Aim, Shoot, and Ricochet""",
        description="""Earn the gold trophy in Hook, Line, and Skimmer without using the bazooka more than 4 times""",
        points=5,
        badge="00000",
    ),
    615928: Achievement(
        id=615928,
        title="""Booth Fraud""",
        description="""Kill all enemy worms in Nobody Rides For Free""",
        points=10,
        badge="00000",
    ),
    615929: Achievement(
        id=615929,
        title="""Diplomatic Negotiation""",
        description="""Earn the gold trophy in Hold Until Relieved without killing any enemy worm""",
        points=5,
        badge="00000",
    ),
    615930: Achievement(
        id=615930,
        title="""Only Up!""",
        description="""Earn the gold trophy in To Boldly Go without jumping more than 10 times""",
        points=10,
        badge="00000",
    ),
    615931: Achievement(
        id=615931,
        title="""Up, up and Away!""",
        description="""Earn the gold trophy in Beautiful Balloon without collecting fuel crates or using the homing missile""",
        points=5,
        badge="00000",
    ),
    615932: Achievement(
        id=615932,
        title="""Counting Sheep""",
        description="""Earn the gold trophy in A Good Nights Sleep in no more than 3 turns""",
        points=5,
        badge="00000",
    ),
    615933: Achievement(
        id=615933,
        title="""Flooding the Vermin""",
        description="""Make all enemy worms in Beefcake Breakfast Brawl die during the same turn""",
        points=10,
        badge="00000",
    ),
    615934: Achievement(
        id=615934,
        title="""Minesweeper""",
        description="""Earn the gold trophy in Costa Del Danger without taking damage""",
        points=5,
        badge="00000",
    ),
    615935: Achievement(
        id=615935,
        title="""The Viking Way""",
        description="""Earn the gold trophy in Ragnarok and Roll only using melee attacks""",
        points=10,
        badge="00000",
    ),
    615936: Achievement(
        id=615936,
        title="""Technophobe""",
        description="""Earn the gold trophy in Alien Juice Suckers without using the teleporter, jetpack or homing missile""",
        points=10,
        badge="00000",
    ),
    616025: Achievement(
        id=616025,
        title="""Sink Fast""",
        description="""Win a 4 vs. 4 worms round against a CPU team on difficulty PERFECT with the Sudden Sinking scheme on the Costa Del Danger landscape [No Wormpot]""",
        points=5,
        badge="00000",
    ),
    616026: Achievement(
        id=616026,
        title="""Bazooka and Grenades""",
        description="""Win a 4 vs. 4 worms round against a CPU team on difficulty PERFECT with the BnG scheme on the Please No More Islands landscape [No Wormpot]""",
        points=5,
        badge="00000",
    ),
    616027: Achievement(
        id=616027,
        title="""Off to Go Shopping""",
        description="""Win a 4 vs. 4 worms round against a CPU team on difficulty PERFECT with the Shopping scheme on the Jetpack Challenge 1 landscape [No Wormpot]""",
        points=5,
        badge="00000",
    ),
    616028: Achievement(
        id=616028,
        title="""Meet the Sniper""",
        description="""Win a 4 vs. 4 worms round against a CPU team on difficulty PERFECT with the Sniper scheme on the Return of the Chateau Assassin landscape [No Wormpot]""",
        points=5,
        badge="00000",
    ),
    616029: Achievement(
        id=616029,
        title="""Standing Strong Against Kong""",
        description="""Win a 4 vs. 4 worms round against a CPU team on difficulty GOOD or higher with the Stand and Deliver scheme on The Mighty Kong landscape [No Wormpot]""",
        points=10,
        badge="00000",
    ),
    616024: Achievement(
        id=616024,
        title="""[Void]""",
        description="""Void""",
        points=0,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    163325: Leaderboard(
        id=163325,
        title="""Gold Trophy Time Tracker""",
        description="""Hold L1 and R1 for 3 seconds in the main menu to activate or deactivate the time tracker for gold trophies""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163408: Leaderboard(
        id=163408,
        title="""Shotgun Challenge 1""",
        description="""Score the highest time in the Shotgun Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163409: Leaderboard(
        id=163409,
        title="""Shotgun Challenge 2""",
        description="""Score the highest time in the Shotgun Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163410: Leaderboard(
        id=163410,
        title="""Shotgun Challenge 3""",
        description="""Score the highest time in the Shotgun Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163411: Leaderboard(
        id=163411,
        title="""Super Sheep Challenge 1""",
        description="""Score the highest time in the Super Sheep Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163412: Leaderboard(
        id=163412,
        title="""Super Sheep Challenge 2""",
        description="""Score the highest time in the Super Sheep Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163413: Leaderboard(
        id=163413,
        title="""Super Sheep Challenge 3""",
        description="""Score the highest time in the Super Sheep Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163414: Leaderboard(
        id=163414,
        title="""Jetpack Challenge 1""",
        description="""Score the highest time in the Jetpack Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163415: Leaderboard(
        id=163415,
        title="""Jetpack Challenge 2""",
        description="""Score the highest time in the Jetpack Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163416: Leaderboard(
        id=163416,
        title="""Jetpack Challenge 3""",
        description="""Score the highest time in the Jetpack Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163417: Leaderboard(
        id=163417,
        title="""Parachute Challenge 1""",
        description="""Score the highest time in the Parachute Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163418: Leaderboard(
        id=163418,
        title="""Parachute Challenge 2""",
        description="""Score the highest time in the Parachute Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163419: Leaderboard(
        id=163419,
        title="""Parachute Challenge 3""",
        description="""Score the highest time in the Parachute Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    163420: Leaderboard(
        id=163420,
        title="""Deathmatch Challenge 1""",
        description="""Score the lowest time in the Deathmatch Challenge 1""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163421: Leaderboard(
        id=163421,
        title="""Deathmatch Challenge 2""",
        description="""Score the lowest time in the Deathmatch Challenge 2""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163422: Leaderboard(
        id=163422,
        title="""Deathmatch Challenge 3""",
        description="""Score the lowest time in the Deathmatch Challenge 3""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163423: Leaderboard(
        id=163423,
        title="""Deathmatch Challenge 4""",
        description="""Score the lowest time in the Deathmatch Challenge 4""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163424: Leaderboard(
        id=163424,
        title="""Deathmatch Challenge 5""",
        description="""Score the lowest time in the Deathmatch Challenge 5""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163425: Leaderboard(
        id=163425,
        title="""Deathmatch Challenge 6""",
        description="""Score the lowest time in the Deathmatch Challenge 6""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163426: Leaderboard(
        id=163426,
        title="""Deathmatch Challenge 7""",
        description="""Score the lowest time in the Deathmatch Challenge 7""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163427: Leaderboard(
        id=163427,
        title="""Deathmatch Challenge 8""",
        description="""Score the lowest time in the Deathmatch Challenge 8""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163428: Leaderboard(
        id=163428,
        title="""Deathmatch Challenge 9""",
        description="""Score the lowest time in the Deathmatch Challenge 9""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163429: Leaderboard(
        id=163429,
        title="""Deathmatch Challenge 10""",
        description="""Score the lowest time in the Deathmatch Challenge 10""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164779: Leaderboard(
        id=164779,
        title="""Time Trial - Atlantis Training Facility""",
        description="""Complete Atlantis Training Facility as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164780: Leaderboard(
        id=164780,
        title="""Time Trial - Down in the Dumps""",
        description="""Complete Down in the Dumps as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164781: Leaderboard(
        id=164781,
        title="""Time Trial - Return to Chateau Assassin""",
        description="""Complete Return to Chateau Assassin as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164782: Leaderboard(
        id=164782,
        title="""Time Trial - The Mighty Kong""",
        description="""Complete The Mighty Kong as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164783: Leaderboard(
        id=164783,
        title="""Time Trial - Test Tubes""",
        description="""Complete Test Tubes as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164784: Leaderboard(
        id=164784,
        title="""Time Trial - D-Day""",
        description="""Complete D-Day as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164785: Leaderboard(
        id=164785,
        title="""Time Trial - Crate Britain""",
        description="""Complete Crate Britain as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164786: Leaderboard(
        id=164786,
        title="""Time Trial - Grave Danger""",
        description="""Complete Grave Danger as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164787: Leaderboard(
        id=164787,
        title="""Time Trial - A Leek in a Vegetable Patch""",
        description="""Complete A Leek in a Vegetable Patch as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    164788: Leaderboard(
        id=164788,
        title="""Time Trial - Ice, Ice, Maybe""",
        description="""Complete Ice, Ice, Maybe as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=False,
    ),
    164789: Leaderboard(
        id=164789,
        title="""Time Trial - When Annelids Collide""",
        description="""Complete When Annelids Collide as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163430: Leaderboard(
        id=163430,
        title="""Time Trial - Rum Deal""",
        description="""Complete Rum Deal as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164790: Leaderboard(
        id=164790,
        title="""Time Trial - Earn Your Crust""",
        description="""Complete Earn Your Crust as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164791: Leaderboard(
        id=164791,
        title="""Time Trial - Apple Core Island""",
        description="""Complete Apple Core Island as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164792: Leaderboard(
        id=164792,
        title="""Time Trial - Helter Skelter""",
        description="""Complete Helter Skelter as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163431: Leaderboard(
        id=163431,
        title="""Time Trial - Take My Cherry""",
        description="""Complete Take My Cherry as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164793: Leaderboard(
        id=164793,
        title="""Time Trial - In Space, No-One Can Hear You Clean""",
        description="""Complete In Space, No-One Can Hear You Clean as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164794: Leaderboard(
        id=164794,
        title="""Time Trial - Shiver Me Timbers""",
        description="""Complete Shiver Me Timbers as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163432: Leaderboard(
        id=163432,
        title="""Time Trial - Falling For You""",
        description="""Complete Falling For You as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164795: Leaderboard(
        id=164795,
        title="""Time Trial - Crop Circle""",
        description="""Complete Crop Circle as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164796: Leaderboard(
        id=164796,
        title="""Time Trial - Tree Village Trouble""",
        description="""Complete Tree Village Trouble as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164797: Leaderboard(
        id=164797,
        title="""Time Trial - Movie Mayhem""",
        description="""Complete Movie Mayhem as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163433: Leaderboard(
        id=163433,
        title="""Time Trial - Worm and the Beanstalk""",
        description="""Complete Worm and the Beanstalk as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164798: Leaderboard(
        id=164798,
        title="""Time Trial - School's in for Summer""",
        description="""Complete School's in for Summer as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164799: Leaderboard(
        id=164799,
        title="""Time Trial - High Stakes""",
        description="""Complete High Stakes as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164800: Leaderboard(
        id=164800,
        title="""Time Trial - A Quick Fix""",
        description="""Complete A Quick Fix as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164801: Leaderboard(
        id=164801,
        title="""Time Trial - All Cooped Up""",
        description="""Complete All Cooped Up as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163434: Leaderboard(
        id=163434,
        title="""Time Trial - Trial of the Damned""",
        description="""Complete Trial of the Damned as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164805: Leaderboard(
        id=164805,
        title="""Time Trial - Showdown at the OK Corale Reef""",
        description="""Complete Showdown at the OK Corale Reef as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163435: Leaderboard(
        id=163435,
        title="""Time Trial - Plaice Holder""",
        description="""Complete Plaice Holder as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164802: Leaderboard(
        id=164802,
        title="""Time Trial - Hook, Line, and Skimmer""",
        description="""Complete Hook, Line, and Skimmer as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164806: Leaderboard(
        id=164806,
        title="""Time Trial - Nobody Rides For Free""",
        description="""Complete Nobody Rides For Free as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164803: Leaderboard(
        id=164803,
        title="""Time Trial - Hold Until Relieved""",
        description="""Complete Hold Until Relieved as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163436: Leaderboard(
        id=163436,
        title="""Time Trial - To Boldly Go""",
        description="""Complete To Boldly Go as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    165080: Leaderboard(
        id=165080,
        title="""Least Jumps - To Boldly Go""",
        description="""Complete To Boldly Go in the least amount of jumps""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    164807: Leaderboard(
        id=164807,
        title="""Time Trial - Beautiful Balloon""",
        description="""Complete Beautiful Balloon as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163437: Leaderboard(
        id=163437,
        title="""Time Trial - A Good Nights Sleep""",
        description="""Complete A Good Nights Sleep as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164808: Leaderboard(
        id=164808,
        title="""Time Trial - Beefcake Breakfast Brawl""",
        description="""Complete Beefcake Breakfast Brawl as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    163438: Leaderboard(
        id=163438,
        title="""Time Trial - Costa Del Danger""",
        description="""Complete Costa Del Danger as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164804: Leaderboard(
        id=164804,
        title="""Time Trial - Ragnarok and Roll""",
        description="""Complete Ragnarok and Roll as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
    164809: Leaderboard(
        id=164809,
        title="""Time Trial - Alien Juice Suckers""",
        description="""Complete Alien Juice Suckers as fast as possible""",
        format=LeaderboardFormat.MILLISECS,
        lower_is_better=True,
    ),
})