from logic import Unlock, GameMode, Mission

UNLOCKS = [
    Unlock("L.L.Counting", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Leek", Unlock.Type.LANDSCAPE),
    Unlock("L.P.Pinball", Unlock.Type.WORMAPEDIA),
    Unlock("L.L.Alien", Unlock.Type.LANDSCAPE),
    Unlock("L.Sch.All", Unlock.Type.SCHEME),
    Unlock("L.L.Cooped", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Apple", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Atlantis", Unlock.Type.LANDSCAPE),
    Unlock("L.W.Banana", Unlock.Type.WEAPON),
    Unlock("L.P.Pete", Unlock.Type.WORMAPEDIA),
    Unlock("L.W.BridgeK", Unlock.Type.WEAPON),
    Unlock("L.P.Bright", Unlock.Type.WORMAPEDIA),
    Unlock("L.P.Chatter", Unlock.Type.WORMAPEDIA),
    Unlock("L.P.Donkey", Unlock.Type.WORMAPEDIA),
    Unlock("L.L.Holiday", Unlock.Type.LANDSCAPE),
    Unlock("L.L.CrateBritain", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Crop", Unlock.Type.LANDSCAPE),
    Unlock("L.L.DDay", Unlock.Type.LANDSCAPE),
    Unlock("L.P.Darkside", Unlock.Type.WORMAPEDIA),
    Unlock("L.C.DM1", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM10", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM2", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM3", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM4", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM5", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM6", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM7", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM8", Unlock.Type.CHALLENGE),
    Unlock("L.C.DM9", Unlock.Type.CHALLENGE),
    Unlock("L.L.Crust", Unlock.Type.LANDSCAPE),
    Unlock("L.W.EQuake", Unlock.Type.WEAPON),
    Unlock("L.P.Tapper", Unlock.Type.WORMAPEDIA),
    Unlock("L.P.Fools", Unlock.Type.WORMAPEDIA),
    Unlock("L.S.Lover", Unlock.Type.VOICE),
    Unlock("L.S.Gramps", Unlock.Type.VOICE),
    Unlock("L.L.Graveyard", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Helter", Unlock.Type.LANDSCAPE),
    Unlock("L.L.High", Unlock.Type.LANDSCAPE),
    Unlock("L.S.Horror", Unlock.Type.VOICE),
    Unlock("L.L.Ice", Unlock.Type.LANDSCAPE),
    Unlock("L.C.JP1", Unlock.Type.CHALLENGE),
    Unlock("L.L.Cratefun", Unlock.Type.LANDSCAPE),
    Unlock("L.C.JP2", Unlock.Type.CHALLENGE),
    Unlock("L.C.JP3", Unlock.Type.CHALLENGE),
    Unlock("L.P.Lightside", Unlock.Type.WORMAPEDIA),
    Unlock("L.P.LandD", Unlock.Type.WORMAPEDIA),
    Unlock("L.W.MadCow", Unlock.Type.WEAPON),
    Unlock("L.S.Mad", Unlock.Type.VOICE),
    Unlock("L.L.Landing", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Funfair", Unlock.Type.LANDSCAPE),
    Unlock("L.W.Nuke", Unlock.Type.WEAPON),
    Unlock("L.C.P1", Unlock.Type.CHALLENGE),
    Unlock("L.C.P2", Unlock.Type.CHALLENGE),
    Unlock("L.C.P3", Unlock.Type.CHALLENGE),
    Unlock("L.P.Pink", Unlock.Type.WORMAPEDIA),
    Unlock("L.L.Plaice", Unlock.Type.LANDSCAPE),
    Unlock("L.Sch.Pro", Unlock.Type.SCHEME),
    Unlock("L.L.Ragna", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Chateau", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Schools", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Timbers", Unlock.Type.LANDSCAPE),
    Unlock("L.C.Shotgun2", Unlock.Type.CHALLENGE),
    Unlock("L.C.Shotgun3", Unlock.Type.CHALLENGE),
    Unlock("L.L.Showdown", Unlock.Type.LANDSCAPE),
    Unlock("L.Sch.WBnG", Unlock.Type.SCHEME),
    Unlock("L.Sch.Sniping", Unlock.Type.SCHEME),
    Unlock("L.P.Beatbox", Unlock.Type.WORMAPEDIA),
    Unlock("L.Sch.Sticky", Unlock.Type.SCHEME),
    Unlock("L.C.SS1", Unlock.Type.CHALLENGE),
    Unlock("L.C.SS2", Unlock.Type.CHALLENGE),
    Unlock("L.C.SS3", Unlock.Type.CHALLENGE),
    Unlock("L.W.SSheep", Unlock.Type.WEAPON),
    Unlock("L.S.Villain", Unlock.Type.VOICE),
    Unlock("L.L.Cherry", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Tubes", Unlock.Type.LANDSCAPE),
    Unlock("L.P.Giraffe", Unlock.Type.WORMAPEDIA),
    Unlock("L.P.Horror", Unlock.Type.WORMAPEDIA),
    Unlock("L.P.Lost", Unlock.Type.WORMAPEDIA),
    Unlock("L.L.Kong", Unlock.Type.LANDSCAPE),
    Unlock("L.P.Sally", Unlock.Type.WORMAPEDIA),
    Unlock("L.P.Story", Unlock.Type.WORMAPEDIA),
    Unlock("L.L.Tree", Unlock.Type.LANDSCAPE),
    Unlock("L.L.Collide", Unlock.Type.LANDSCAPE),
    Unlock("L.P.Proto", Unlock.Type.WORMAPEDIA),
]

class Missions:
    TUTORIAL1 = Mission(
        index=0,
        mtype=GameMode.TUTORIAL,
        name="Atlantis Training Facility",
        filename="tutorial1",
        gold=None,
        land_maxheight=None,
        teams=[],
    )
    TUTORIAL2 = Mission(
        index=1,
        mtype=GameMode.TUTORIAL,
        name="Down in the Dumps",
        filename="tutorial2",
        gold=None,
        land_maxheight=None,
        teams=[],
    )
    TUTORIAL3 = Mission(
        index=2,
        mtype=GameMode.TUTORIAL,
        name="Return to Chateau Assassin",
        filename="Tutorial3",
        gold=None,
        land_maxheight=None,
        teams=[],
    )
    TUTORIAL4 = Mission(
        index=3,
        mtype=GameMode.TUTORIAL,
        name="The Mighty Kong",
        filename="Tutorial4",
        gold=None,
        land_maxheight=None,
        teams=[],
    )
    TUTORIAL5 = Mission(
        index=4,
        mtype=GameMode.TUTORIAL,
        name="Test Tubes",
        filename="tutorial5",
        gold=None,
        land_maxheight=None,
        teams=[],
    )
    DRIVING = Mission(
        index=5,
        mtype=GameMode.TUTORIAL,
        name="The Driving Range",
        filename="driving",
        gold=None,
        land_maxheight=None,
        teams=[],
    )
    DDAY = Mission(
        index=0,
        mtype=GameMode.CAMPAIGN,
        name="D-Day",
        filename="dday",
        gold=420000,
        land_maxheight=None,
        teams=[],
    )
    CRATEBRITAIN = Mission(
        index=1,
        mtype=GameMode.CAMPAIGN,
        name="Crate Britain",
        filename="CrateBritain",
        gold=180000,
        land_maxheight=None,
        teams=[],
    )
    GRAVEYARD = Mission(
        index=2,
        mtype=GameMode.CAMPAIGN,
        name="Grave Danger",
        filename="graveyard",
        gold=270000,
        land_maxheight=None,
        teams=[],
    )
    LEEK = Mission(
        index=3,
        mtype=GameMode.CAMPAIGN,
        name="A Leek in a Vegetable Patch",
        filename="leek",
        gold=390000,
        land_maxheight=None,
        teams=[],
    )
    ICE = Mission(
        index=4,
        mtype=GameMode.CAMPAIGN,
        name="Ice, Ice, Maybe",
        filename="ICE",
        gold=240000,
        land_maxheight=None,
        teams=[],
    )
    COLLIDE = Mission(
        index=5,
        mtype=GameMode.CAMPAIGN,
        name="When Annelids Collide",
        filename="Collide",
        gold=270000,
        land_maxheight=None,
        teams=[],
    )
    RUM = Mission(
        index=6,
        mtype=GameMode.CAMPAIGN,
        name="Rum Deal",
        filename="rum",
        gold=120000,
        land_maxheight=None,
        teams=[],
    )
    CRUST = Mission(
        index=7,
        mtype=GameMode.CAMPAIGN,
        name="Earn Your Crust",
        filename="crust",
        gold=180000,
        land_maxheight=None,
        teams=[],
    )
    APPLECORE = Mission(
        index=8,
        mtype=GameMode.CAMPAIGN,
        name="Apple Core Island",
        filename="applecore",
        gold=120000,
        land_maxheight=None,
        teams=[],
    )
    HELTERSKELTER = Mission(
        index=9,
        mtype=GameMode.CAMPAIGN,
        name="Helter Skelter",
        filename="helterskelter",
        gold=210000,
        land_maxheight=None,
        teams=[],
    )
    CHERRY = Mission(
        index=10,
        mtype=GameMode.CAMPAIGN,
        name="Take My Cherry",
        filename="cherry",
        gold=170000,
        land_maxheight=None,
        teams=[],
    )
    CLEAN = Mission(
        index=11,
        mtype=GameMode.CAMPAIGN,
        name="In Space, No-One Can Hear You Clean",
        filename="clean",
        gold=230000,
        land_maxheight=None,
        teams=[],
    )
    TIMBERS = Mission(
        index=12,
        mtype=GameMode.CAMPAIGN,
        name="Shiver Me Timbers",
        filename="timbers",
        gold=440000,
        land_maxheight=None,
        teams=[],
    )
    FALLING = Mission(
        index=13,
        mtype=GameMode.CAMPAIGN,
        name="Falling For You",
        filename="FALLING",
        gold=230000,
        land_maxheight=None,
        teams=[],
    )
    CROPCIRCLE = Mission(
        index=14,
        mtype=GameMode.CAMPAIGN,
        name="Crop Circle",
        filename="cropcircle",
        gold=800000,
        land_maxheight=None,
        teams=[],
    )
    TREEVILLAGE = Mission(
        index=15,
        mtype=GameMode.CAMPAIGN,
        name="Tree Village Trouble",
        filename="treevillage",
        gold=330000,
        land_maxheight=None,
        teams=[],
    )
    LANDING = Mission(
        index=16,
        mtype=GameMode.CAMPAIGN,
        name="Movie Mayhem",
        filename="landing",
        gold=270000,
        land_maxheight=None,
        teams=[],
    )
    BEANSTALK = Mission(
        index=17,
        mtype=GameMode.CAMPAIGN,
        name="Worm and the Beanstalk",
        filename="beanstalk",
        gold=130000,
        land_maxheight=None,
        teams=[],
    )
    SCHOOLS = Mission(
        index=18,
        mtype=GameMode.CAMPAIGN,
        name="School's in for Summer",
        filename="SCHOOLS",
        gold=540000,
        land_maxheight=None,
        teams=[],
    )
    HIGHSTAKES = Mission(
        index=19,
        mtype=GameMode.CAMPAIGN,
        name="High Stakes",
        filename="highstakes",
        gold=780000,
        land_maxheight=None,
        teams=[],
    )
    NOTPC = Mission(
        index=20,
        mtype=GameMode.CAMPAIGN,
        name="A Quick Fix",
        filename="notpc",
        gold=340000,
        land_maxheight=None,
        teams=[],
    )
    COOPED = Mission(
        index=21,
        mtype=GameMode.CAMPAIGN,
        name="All Cooped Up",
        filename="cooped",
        gold=340000,
        land_maxheight=None,
        teams=[],
    )
    TRIAL = Mission(
        index=22,
        mtype=GameMode.CAMPAIGN,
        name="Trial of the Damned",
        filename="TRIAL",
        gold=210000,
        land_maxheight=None,
        teams=[],
    )
    SHOWDOWN = Mission(
        index=23,
        mtype=GameMode.CAMPAIGN,
        name="Showdown at the OK Corale Reef",
        filename="SHOWDOWN",
        gold=270000,
        land_maxheight=None,
        teams=[],
    )
    PLAICE = Mission(
        index=24,
        mtype=GameMode.CAMPAIGN,
        name="Plaice Holder",
        filename="plaice",
        gold=290000,
        land_maxheight=None,
        teams=[],
    )
    HOOKLINE = Mission(
        index=25,
        mtype=GameMode.CAMPAIGN,
        name="Hook, Line, and Skimmer",
        filename="hookline",
        gold=310000,
        land_maxheight=None,
        teams=[],
    )
    FUNFAIR = Mission(
        index=26,
        mtype=GameMode.CAMPAIGN,
        name="Nobody Rides For Free",
        filename="funfair",
        gold=195000,
        land_maxheight=None,
        teams=[],
    )
    PEGASUS = Mission(
        index=27,
        mtype=GameMode.CAMPAIGN,
        name="Hold Until Relieved",
        filename="Pegasus",
        gold=660000,
        land_maxheight=None,
        teams=[],
    )
    BOLDLY = Mission(
        index=28,
        mtype=GameMode.CAMPAIGN,
        name="To Boldly Go",
        filename="boldly",
        gold=50000,
        land_maxheight=None,
        teams=[],
    )
    BALLOON = Mission(
        index=29,
        mtype=GameMode.CAMPAIGN,
        name="Beautiful Balloon",
        filename="balloon",
        gold=240000,
        land_maxheight=None,
        teams=[],
    )
    COUNTINGSHEEP = Mission(
        index=30,
        mtype=GameMode.CAMPAIGN,
        name="A Good Nights Sleep",
        filename="countingsheep",
        gold=240000,
        land_maxheight=None,
        teams=[],
    )
    BREAKFAST = Mission(
        index=31,
        mtype=GameMode.CAMPAIGN,
        name="Beefcake Breakfast Brawl",
        filename="BREAKFAST",
        gold=870000,
        land_maxheight=None,
        teams=[],
    )
    HOLIDAY = Mission(
        index=32,
        mtype=GameMode.CAMPAIGN,
        name="Costa Del Danger",
        filename="holiday",
        gold=255000,
        land_maxheight=None,
        teams=[],
    )
    PACK = Mission(
        index=33,
        mtype=GameMode.CAMPAIGN,
        name="Ragnarok and Roll",
        filename="pack",
        gold=490000,
        land_maxheight=None,
        teams=[],
    )
    ALIEN = Mission(
        index=34,
        mtype=GameMode.CAMPAIGN,
        name="Alien Juice Suckers",
        filename="ALIEN",
        gold=755000,
        land_maxheight=None,
        teams=[],
    )
    TARGETHUNT = Mission(
        index=0,
        mtype=GameMode.CHALLENGE,
        name="Shotgun Challenge 1",
        filename="TargetHunt",
        gold=425400,
        land_maxheight=0x44113984,
        teams=[],
    )
    TARGETHUNT2 = Mission(
        index=1,
        mtype=GameMode.CHALLENGE,
        name="Shotgun Challenge 2",
        filename="TargetHunt2",
        gold=214200,
        land_maxheight=0x452b799b,
        teams=[],
    )
    HOMING = Mission(
        index=2,
        mtype=GameMode.CHALLENGE,
        name="Shotgun Challenge 3",
        filename="HOMING",
        gold=190600,
        land_maxheight=0x444731d8,
        teams=[],
    )
    SHEEP1 = Mission(
        index=3,
        mtype=GameMode.CHALLENGE,
        name="Super Sheep Challenge 1",
        filename="Sheep1",
        gold=306600,
        land_maxheight=0x453f9645,
        teams=[],
    )
    SHEEP2 = Mission(
        index=4,
        mtype=GameMode.CHALLENGE,
        name="Super Sheep Challenge 2",
        filename="Sheep2",
        gold=244200,
        land_maxheight=0x4415ee12,
        teams=[],
    )
    TARGETHUNT4 = Mission(
        index=5,
        mtype=GameMode.CHALLENGE,
        name="Super Sheep Challenge 3",
        filename="TargetHunt4",
        gold=148200,
        land_maxheight=0x440b8bdc,
        teams=[],
    )
    CRATEFUN = Mission(
        index=6,
        mtype=GameMode.CHALLENGE,
        name="Jet Pack Challenge 1",
        filename="cratefun",
        gold=249600,
        land_maxheight=0x43e75e17,
        teams=[],
    )
    JETPACKCHALL2 = Mission(
        index=7,
        mtype=GameMode.CHALLENGE,
        name="Jet Pack Challenge 2",
        filename="jetpackchall2",
        gold=249600,
        land_maxheight=0x44082017,
        teams=[],
    )
    JETPACKCHALL3 = Mission(
        index=8,
        mtype=GameMode.CHALLENGE,
        name="Jet Pack Challenge 3",
        filename="jetpackchall3",
        gold=144000,
        land_maxheight=0x447aa8dc,
        teams=[],
    )
    CHUTE1 = Mission(
        index=9,
        mtype=GameMode.CHALLENGE,
        name="Parachute Challenge 1",
        filename="Chute1",
        gold=307200,
        land_maxheight=0x452b799b,
        teams=[],
    )
    CHUTE2 = Mission(
        index=10,
        mtype=GameMode.CHALLENGE,
        name="Parachute Challenge 2",
        filename="chute2",
        gold=259200,
        land_maxheight=0x44ab25d0,
        teams=[],
    )
    CHUTE3 = Mission(
        index=11,
        mtype=GameMode.CHALLENGE,
        name="Parachute Challenge 3",
        filename="chute3",
        gold=138600,
        land_maxheight=0x4507f262,
        teams=[],
    )
    DEATHMATCH1 = Mission(
        index=12,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 1",
        filename="Deathmatch1",
        gold=394000,
        land_maxheight=0x43d8a364,
        teams=[],
    )
    DEATHMATCH2 = Mission(
        index=13,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 2",
        filename="Deathmatch2",
        gold=428400,
        land_maxheight=0x43c9ceab,
        teams=[],
    )
    DEATHMATCH3 = Mission(
        index=14,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 3",
        filename="Deathmatch3",
        gold=421000,
        land_maxheight=0x44074e83,
        teams=[],
    )
    DEATHMATCH4 = Mission(
        index=15,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 4",
        filename="Deathmatch4",
        gold=629400,
        land_maxheight=0x43fa352b,
        teams=[],
    )
    DEATHMATCH5 = Mission(
        index=16,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 5",
        filename="Deathmatch5",
        gold=555600,
        land_maxheight=0x43cff6eb,
        teams=[],
    )
    DEATHMATCH6 = Mission(
        index=17,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 6",
        filename="Deathmatch6",
        gold=324600,
        land_maxheight=0x43c0b331,
        teams=[],
    )
    DEATHMATCH7 = Mission(
        index=18,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 7",
        filename="Deathmatch7",
        gold=446400,
        land_maxheight=0x43f0dfac,
        teams=[],
    )
    DEATHMATCH8 = Mission(
        index=19,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 8",
        filename="Deathmatch8",
        gold=574800,
        land_maxheight=0x442bd166,
        teams=[],
    )
    DEATHMATCH9 = Mission(
        index=20,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 9",
        filename="Deathmatch9",
        gold=730800,
        land_maxheight=0x43d4fde2,
        teams=[],
    )
    DEATHMATCH10 = Mission(
        index=21,
        mtype=GameMode.CHALLENGE,
        name="Deathmatch Challenge 10",
        filename="Deathmatch10",
        gold=1165200,
        land_maxheight=0x440b9c29,
        teams=[],
    )

    CAMPAIGN = [
        DDAY,
        CRATEBRITAIN,
        GRAVEYARD,
        LEEK,
        ICE,
        COLLIDE,
        RUM,
        CRUST,
        APPLECORE,
        HELTERSKELTER,
        CHERRY,
        CLEAN,
        TIMBERS,
        FALLING,
        CROPCIRCLE,
        TREEVILLAGE,
        LANDING,
        BEANSTALK,
        SCHOOLS,
        HIGHSTAKES,
        NOTPC,
        COOPED,
        TRIAL,
        SHOWDOWN,
        PLAICE,
        HOOKLINE,
        FUNFAIR,
        PEGASUS,
        BOLDLY,
        BALLOON,
        COUNTINGSHEEP,
        BREAKFAST,
        HOLIDAY,
        PACK,
        ALIEN
    ]
    TUTORIAL = [
        TUTORIAL1,
        TUTORIAL2,
        TUTORIAL3,
        TUTORIAL4,
        TUTORIAL5,
        DRIVING
    ]
    CHALLENGE = [
        TARGETHUNT,
        TARGETHUNT2,
        HOMING,
        SHEEP1,
        SHEEP2,
        TARGETHUNT4,
        CRATEFUN,
        JETPACKCHALL2,
        JETPACKCHALL3,
        CHUTE1,
        CHUTE2,
        CHUTE3,
        DEATHMATCH1,
        DEATHMATCH2,
        DEATHMATCH3,
        DEATHMATCH4,
        DEATHMATCH5,
        DEATHMATCH6,
        DEATHMATCH7,
        DEATHMATCH8,
        DEATHMATCH9,
        DEATHMATCH10
    ]