from pycheevos.core.condition import ConditionList
from pycheevos.core.constants import ADD_SOURCE
from pycheevos.core.helpers import add_address, add_source, byte, delta, dword, dword_be, measured, measured_percent, recall, remember, sub_source, value, group, string_equals, word_be
from pycheevos.core.value import Flag
from pycheevos.models.rich_presence import *

from logic import Context, GameMode, Level, Worms3D, XData, ascii_be
from memory import Memory

def render(conditions: ConditionList):
    return "_".join([cond.render() for cond in conditions])

class WormsRichPresence(RichPresence):
    def __init__(self):
        super().__init__()
        self.game_id = 21184

    def region(self, ctx: Context):
        return {
            "EU": "🇪🇺",
            "US": "🇺🇸",
        }[ctx.region]

    def unlocks(self, ctx: Context):
        unlocks = ConditionList([
            add_source(value(len(Worms3D.UNLOCKS))),
            *[
                sub_source(unlock.locked(ctx))
                for unlock in Worms3D.UNLOCKS
            ],
            remember(value(0)),
            remember(recall() * 100),
            measured(recall() / len(Worms3D.UNLOCKS)),
        ])
        return f"🔓@Number({render(unlocks)})%"

    def challenge(self, ctx: Context):
        return group(
            add_source(XData.get_value(ctx, "Land.InitialMaxHeight")),
            measured(dword_be(Worms3D.current_script(ctx)))
        )

    def level_hash(self, ctx: Context):
        return group(
            add_source(Worms3D.current_gamemode(ctx) * value(100)),
            Worms3D.current_mission(ctx)
        ).with_flag(Flag.MEASURED)
            # measured(Worms3D.current_mission(ctx))
    

    def generate(self):
        self.add_lookup(
            "Level", 
            values={
                0x12c: "Atlantis Training Facility",
                0x12d: "Down in the Dumps",
                0x12e: "Return to Chateau Assassin",
                0x12f: "The Mighty Kong",
                0x130: "Test Tubes",
                0x131: "The Driving Range",
                0x0: "D-Day",
                0x1: "Crate Britain",
                0x2: "Grave Danger",
                0x3: "A Leek in a Vegetable Patch",
                0x4: "Ice, Ice, Maybe",
                0x5: "When Annelids Collide",
                0x6: "Rum Deal",
                0x7: "Earn Your Crust",
                0x8: "Apple Core Island",
                0x9: "Helter Skelter",
                0xa: "Take My Cherry",
                0xb: "In Space, No-One Can Hear You Clean",
                0xc: "Shiver Me Timbers",
                0xd: "Falling For You",
                0xe: "Crop Circle",
                0xf: "Tree Village Trouble",
                0x10: "Movie Mayhem",
                0x11: "Worm and the Beanstalk",
                0x12: "School's in for Summer",
                0x13: "High Stakes",
                0x14: "A Quick Fix",
                0x15: "All Cooped Up",
                0x16: "Trial of the Damned",
                0x17: "Showdown at the OK Corale Reef",
                0x18: "Plaice Holder",
                0x19: "Hook, Line, and Skimmer",
                0x1a: "Nobody Rides For Free",
                0x1b: "Hold Until Relieved",
                0x1c: "To Boldly Go",
                0x1d: "Beautiful Balloon",
                0x1e: "A Good Nights Sleep",
                0x1f: "Beefcake Breakfast Brawl",
                0x20: "Costa Del Danger",
                0x21: "Ragnarok and Roll",
                0x22: "Alien Juice Suckers",
            },
            default=""
        )
        self.add_lookup(
            "GameMode",
            values={
                0x3: "🎯Tutorial",
                0x0: "🗺️Campaign",
                0x4: "🏆Challenge",
            }
        )
        # Hashes generated by adding the value of Land.InitialMaxHeight and the first 4 bytes of the LUA script name
        self.add_lookup(
            "Challenge",
            values={
                0x9872abeb: "Shotgun Challenge 1",
                0x998cec02: "Shotgun Challenge 2",
                0x8c967f21: "Shotgun Challenge 3",
                0x98a7fbaa: "Super Sheep Challenge 1",
                0x977e5377: "Super Sheep Challenge 2",
                0x986cfe43: "Super Sheep Challenge 3",
                0xa759bf8b: "Jet Pack Challenge 1",
                0xae6d9487: "Jet Pack Challenge 2",
                0xaee01d4c: "Jet Pack Challenge 3",
                0x8893ef0f: "Parachute Challenge 1",
                0xa8139b44: "Parachute Challenge 2",
                0xa87067d6: "Parachute Challenge 3",
                0x883e04d8: "Deathmatch Challenge 1",
                0x882f301f: "Deathmatch Challenge 2",
                0x886caff7: "Deathmatch Challenge 3",
                0x885f969f: "Deathmatch Challenge 4",
                0x8835585f: "Deathmatch Challenge 5",
                0x882614a5: "Deathmatch Challenge 6",
                0x88564120: "Deathmatch Challenge 7",
                0x889132da: "Deathmatch Challenge 8",
                0x883a5f56: "Deathmatch Challenge 9",
                0x8870fd9d: "Deathmatch Challenge 10",
            },
            default=""
        )
        for ctx in [Context("US"), Context("EU")]:
            self.add_display(
                (
                    Worms3D.check_serial(ctx) &
                    Worms3D.is_loading(ctx)
                ),
                f"⏳Loading... • {self.region(ctx)}"
            )
            self.add_display(
                (
                    Worms3D.check_serial(ctx) &
                    Worms3D.is_watching_cutscene(ctx)
                ),
                f"Watching a cutscene • {self.region(ctx)}"
            )
            self.add_display(
                (
                    Worms3D.check_serial(ctx) &
                    Worms3D.is_in_menu(ctx)
                ),
                f"In the main menu • {self.unlocks(ctx)} • {self.region(ctx)}"
            )
            self.add_display(
                (
                    Worms3D.check_serial(ctx) &
                    Worms3D.is_ingame(ctx) &
                    (string_equals(Worms3D.current_script(ctx), "stdv"))
                ),
                f"👥Multiplayer • 🗺️Custom Map • {self.unlocks(ctx)} • {self.region(ctx)}"
            )
            self.add_display(
                (
                    Worms3D.check_serial(ctx) &
                    Worms3D.is_ingame(ctx) &
                    (dword_be(Worms3D.current_script(ctx)) != value(ascii_be("stdv")))
                ),
                f"@GameMode({measured(Worms3D.current_gamemode(ctx))}) • 🗺️@Challenge({self.challenge(ctx)})@Level({self.level_hash(ctx)}) • {self.unlocks(ctx)} • {self.region(ctx)}"
            )
        self.add_display(None, "Playing Worms 3D")


if __name__=="__main__":
    Worms3D.init()
    rp = WormsRichPresence()
    rp.generate()
    rp.save(rp.game_id, path="output/")

