from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    578904: Achievement(
        id=578904,
        title="""Warning: Cheat Codes""",
        description="""While not strictly forbidden, using cheat codes will reset any active challenge or leaderboard. Use at your own risk""",
        points=0,
        badge="657020",
    ),
    573032: Achievement(
        id=573032,
        title="""Extra Life""",
        description="""Obtain an extra life by collecting 100 Tings""",
        points=3,
        badge="656963",
    ),
    573033: Achievement(
        id=573033,
        title="""Livingstone Havoc""",
        description="""Perform a grimace to scare a tall Livingstone""",
        points=1,
        badge="656964",
        type=AchievementType.MISSABLE,
    ),
    574649: Achievement(
        id=574649,
        title="""Magician of the Dream Forest""",
        description="""Clear the first Magician bonus level in Pink Plant Woods""",
        points=5,
        badge="656686",
    ),
    574636: Achievement(
        id=574636,
        title="""One Punch Rayman""",
        description="""Meet Betilla the Fairy for the first time and learn to punch using your fist""",
        points=1,
        badge="656965",
        type=AchievementType.PROGRESSION,
    ),
    574650: Achievement(
        id=574650,
        title="""Enchanted Woods""",
        description="""Clear the second Magician bonus level in Pink Plant Woods""",
        points=5,
        badge="656687",
    ),
    574641: Achievement(
        id=574641,
        title="""Bezzt Friendzz""",
        description="""Defeat Bzzit in Anguish Lagoon""",
        points=5,
        badge="656678",
        type=AchievementType.PROGRESSION,
    ),
    577245: Achievement(
        id=577245,
        title="""The Flight of Power""",
        description="""Collect all the fist and HP power-ups during the flight with Bzzit in Anguish Lagoon without taking damage""",
        points=5,
        badge="656966",
    ),
    574637: Achievement(
        id=574637,
        title="""Hang in There""",
        description="""Learn the ability to hang onto platforms""",
        points=2,
        badge="656967",
        type=AchievementType.PROGRESSION,
    ),
    573034: Achievement(
        id=573034,
        title="""The Walk of Life""",
        description="""Collect all 8 extra lives in Pink Plant Woods""",
        points=5,
        badge="656672",
    ),
    573015: Achievement(
        id=573015,
        title="""Primordial Forest""",
        description="""Break all 6 Electoon cages in Pink Plant Woods""",
        points=5,
        badge="656655",
        type=AchievementType.PROGRESSION,
    ),
    573016: Achievement(
        id=573016,
        title="""Lagoon of Darkness""",
        description="""Break all 6 Electoon cages in Anguish Lagoon""",
        points=5,
        badge="656656",
        type=AchievementType.PROGRESSION,
    ),
    577246: Achievement(
        id=577246,
        title="""Tarayzan's Apprentice""",
        description="""Clear the first segment of The Swamps of Forgetfulness without planting more than 6 seeds""",
        points=5,
        badge="656968",
    ),
    574651: Achievement(
        id=574651,
        title="""Wisdom of the Swamp""",
        description="""Clear the Magician bonus level in The Swamps of Forgetfulness""",
        points=5,
        badge="656688",
    ),
    573017: Achievement(
        id=573017,
        title="""Marshes of Oblivion""",
        description="""Break all 6 Electoon cages in The Swamps of Forgetfulness""",
        points=5,
        badge="656657",
        type=AchievementType.PROGRESSION,
    ),
    574652: Achievement(
        id=574652,
        title="""Forest Sorcery""",
        description="""Clear the Magician bonus level in Moskito's Nest""",
        points=5,
        badge="656689",
    ),
    573499: Achievement(
        id=573499,
        title="""The Creature""",
        description="""Defeat the tentacle flower in Moskito's Nest""",
        points=2,
        badge="656999",
    ),
    577247: Achievement(
        id=577247,
        title="""The Walk of Shame""",
        description="""Punch the plum at the end of Moskito's Nest's second segment then backtrack to the beginning of the segment without dying or saving at the checkpoint""",
        points=5,
        badge="656969",
    ),
    574642: Achievement(
        id=574642,
        title="""Not so Friendly""",
        description="""Defeat Moskito in Moskito's Nest""",
        points=10,
        badge="656679",
        type=AchievementType.PROGRESSION,
    ),
    577251: Achievement(
        id=577251,
        title="""Aedes Raymanis""",
        description="""Defeat Moskito in Moskito's Nest without taking damage""",
        points=10,
        badge="656698",
        type=AchievementType.MISSABLE,
    ),
    574638: Achievement(
        id=574638,
        title="""Froot Loops""",
        description="""Learn the ability to grapple flying rings with your fist""",
        points=3,
        badge="656970",
        type=AchievementType.PROGRESSION,
    ),
    573018: Achievement(
        id=573018,
        title="""Lair of Moskito""",
        description="""Break all 6 Electoon cages in Moskito's Nest""",
        points=5,
        badge="656658",
        type=AchievementType.PROGRESSION,
    ),
    574653: Achievement(
        id=574653,
        title="""Percussive Enchantment""",
        description="""Clear the Magician bonus level in Bongo Hills""",
        points=5,
        badge="656690",
    ),
    573019: Achievement(
        id=573019,
        title="""Butte of Bongos""",
        description="""Break all 6 Electoon cages in Bongo Hills""",
        points=5,
        badge="656659",
        type=AchievementType.PROGRESSION,
    ),
    578893: Achievement(
        id=578893,
        title="""Standing Here I Realize""",
        description="""Attempt to deal damage to a mad drummer by punching him in the face""",
        points=2,
        badge="657012",
    ),
    577248: Achievement(
        id=577248,
        title="""Oops! All Tings""",
        description="""Collect 200 Tings in Bongo Hills and clear the level without dying""",
        points=25,
        badge="656971",
    ),
    574654: Achievement(
        id=574654,
        title="""Magical Jazz""",
        description="""Clear the Magician bonus level in Allegro Presto""",
        points=5,
        badge="656691",
    ),
    573020: Achievement(
        id=573020,
        title="""Fast and Bright""",
        description="""Break all 6 Electoon cages in Allegro Presto""",
        points=5,
        badge="656660",
        type=AchievementType.PROGRESSION,
    ),
    577249: Achievement(
        id=577249,
        title="""Vivace Prestissimo""",
        description="""Clear Allegro Presto under 4:30 before defeating Mr. Sax or having learned running""",
        points=25,
        badge="656972",
        type=AchievementType.MISSABLE,
    ),
    574639: Achievement(
        id=574639,
        title="""Haircopter""",
        description="""Learn the abillity to hover using your hair as an helicopter""",
        points=4,
        badge="656973",
        type=AchievementType.PROGRESSION,
    ),
    573021: Achievement(
        id=573021,
        title="""Celestial Gongs""",
        description="""Break all 6 Electoon cages in Gong Heights""",
        points=5,
        badge="656661",
        type=AchievementType.PROGRESSION,
    ),
    577250: Achievement(
        id=577250,
        title="""Gong Heights Challenge""",
        description="""Clear the autoscroller segment in Gong Heights without taking damage""",
        points=5,
        badge="657000",
    ),
    573022: Achievement(
        id=573022,
        title="""Charivari of Mr. Sax""",
        description="""Break all 6 Electoon cages in Mr. Sax's Hullaballo""",
        points=5,
        badge="656662",
        type=AchievementType.PROGRESSION,
    ),
    578882: Achievement(
        id=578882,
        title="""Smooth Jazz""",
        description="""Clear the replayable segment of Mr Sax's Hullaballo under 2:40""",
        points=10,
        badge="657001",
    ),
    574643: Achievement(
        id=574643,
        title="""Makes Me Move Like a Freak""",
        description="""Defeat Mr. Sax in Mr. Sax's Hullaballo""",
        points=10,
        badge="656680",
    ),
    577252: Achievement(
        id=577252,
        title="""Mr. Saxobeat""",
        description="""Defeat Mr. Sax in Mr. Sax's Hullaballo without taking damage and having dealt at least 6 hits during the chase""",
        points=10,
        badge="656699",
        type=AchievementType.MISSABLE,
    ),
    573023: Achievement(
        id=573023,
        title="""Ravine of Twilight""",
        description="""Break all 6 Electoon cages in Twilight Gulch""",
        points=5,
        badge="656663",
        type=AchievementType.PROGRESSION,
    ),
    578883: Achievement(
        id=578883,
        title="""Experienced Climber""",
        description="""Break all 6 Electoon cages in Twilight Gulch in a single visit. Re-entering the level is allowed as long as you didn't break any cage""",
        points=5,
        badge="657002",
        type=AchievementType.MISSABLE,
    ),
    578894: Achievement(
        id=578894,
        title="""Backdoor Exit""",
        description="""Take the alternate exit in the first segment of The Hard Rocks""",
        points=3,
        badge="657013",
    ),
    574655: Achievement(
        id=574655,
        title="""Sparkly Rocks""",
        description="""Clear the Magician bonus level in The Hard Rocks""",
        points=5,
        badge="656692",
    ),
    578884: Achievement(
        id=578884,
        title="""Rocky Traps""",
        description="""Collect all 6 extra lives in The Hard Rocks""",
        points=5,
        badge="657003",
    ),
    573024: Achievement(
        id=573024,
        title="""The Chaos of Nightmare""",
        description="""Break all 6 Electoon cages in The Hard Rocks""",
        points=5,
        badge="656664",
        type=AchievementType.PROGRESSION,
    ),
    578885: Achievement(
        id=578885,
        title="""Flawless Flying""",
        description="""Clear the first super helicopter segment of Mr Stone's Peaks under 1:45 without taking damage""",
        points=10,
        badge="657004",
    ),
    574656: Achievement(
        id=574656,
        title="""Snowy Peaks""",
        description="""Clear the Magician bonus level in Mr. Stone's Peaks""",
        points=5,
        badge="656693",
    ),
    573025: Achievement(
        id=573025,
        title="""Peaks of Mr. Stone""",
        description="""Break all 6 Electoon cages in Mr. Stone's Peaks""",
        points=5,
        badge="656665",
        type=AchievementType.PROGRESSION,
    ),
    574644: Achievement(
        id=574644,
        title="""Stone Head""",
        description="""Defeat Mr. Stone in Mr. Stone's Peaks""",
        points=10,
        badge="656681",
        type=AchievementType.PROGRESSION,
    ),
    577253: Achievement(
        id=577253,
        title="""Rock and Stone""",
        description="""Defeat Mr. Stone in Mr. Stone's Peaks without taking damage""",
        points=10,
        badge="656700",
        type=AchievementType.MISSABLE,
    ),
    574640: Achievement(
        id=574640,
        title="""Legless Runner""",
        description="""Learn the ability to run""",
        points=5,
        badge="656974",
        type=AchievementType.PROGRESSION,
    ),
    578897: Achievement(
        id=578897,
        title="""Short King""",
        description="""Defeat a flying pirate in Eraser Plains while being in Rayman's tiny form""",
        points=3,
        badge="657016",
    ),
    574657: Achievement(
        id=574657,
        title="""Magic Eraser""",
        description="""Clear the Magician bonus level in Eraser Plains""",
        points=5,
        badge="656694",
    ),
    573026: Achievement(
        id=573026,
        title="""Creek of Pencils""",
        description="""Break all 6 Electoon cages in Eraser Plains""",
        points=5,
        badge="656666",
        type=AchievementType.PROGRESSION,
    ),
    578886: Achievement(
        id=578886,
        title="""Crayon Platformer""",
        description="""Collect 75 Tings in Eraser Plains and clear the replayable segments of the level without dying""",
        points=10,
        badge="657005",
    ),
    574645: Achievement(
        id=574645,
        title="""Absolute Theatre""",
        description="""Defeat Pirate Mama in Eraser Plains""",
        points=5,
        badge="656682",
        type=AchievementType.PROGRESSION,
    ),
    578887: Achievement(
        id=578887,
        title="""Grappling Triathlon""",
        description="""Clear the first segment in Pencil Pentathlon without grappling to flying rings more than 3 times or saving at the checkpoint""",
        points=5,
        badge="657006",
    ),
    573027: Achievement(
        id=573027,
        title="""Thumbtack Panic""",
        description="""Break all 6 Electoon cages in Pencil Pentathlon""",
        points=5,
        badge="656667",
        type=AchievementType.PROGRESSION,
    ),
    578896: Achievement(
        id=578896,
        title="""We're Going Up""",
        description="""Take the higher path exit in the first segment of Space Mama's Crater""",
        points=1,
        badge="657015",
    ),
    578895: Achievement(
        id=578895,
        title="""The Illusion of Choice""",
        description="""Take the lower path exit in the first segment of Space Mama's Crater""",
        points=1,
        badge="657014",
    ),
    574658: Achievement(
        id=574658,
        title="""Space Magician""",
        description="""Clear the Magician bonus level in Space Mama's Crater""",
        points=5,
        badge="656695",
    ),
    573028: Achievement(
        id=573028,
        title="""Crater of Space Mama""",
        description="""Break all 6 Electoon cages in Space Mama's Crater""",
        points=5,
        badge="656668",
        type=AchievementType.PROGRESSION,
    ),
    578888: Achievement(
        id=578888,
        title="""Needle Platformer""",
        description="""Clear the replayable segments of Space Mama's Crater under 5:00""",
        points=25,
        badge="657007",
    ),
    574646: Achievement(
        id=574646,
        title="""Technology from Outer Space""",
        description="""Defeat Space Mama in Space Mama's Crater""",
        points=10,
        badge="656683",
        type=AchievementType.PROGRESSION,
    ),
    577254: Achievement(
        id=577254,
        title="""Revenge of Mere Denis""",
        description="""Defeat Space Mama in Space Mama's Crater without taking damage""",
        points=10,
        badge="656701",
        type=AchievementType.MISSABLE,
    ),
    574659: Achievement(
        id=574659,
        title="""Crystal Ball""",
        description="""Clear the Magician bonus level in Crystal Palace""",
        points=5,
        badge="656696",
    ),
    573029: Achievement(
        id=573029,
        title="""Palace of Crystal""",
        description="""Break all 6 Electoon cages in Crystal Palace""",
        points=5,
        badge="656669",
        type=AchievementType.PROGRESSION,
    ),
    578889: Achievement(
        id=578889,
        title="""Crystallized Haircut""",
        description="""Clear Crystal Palace without hovering using your hair""",
        points=10,
        badge="657008",
    ),
    578890: Achievement(
        id=578890,
        title="""Did You Bring a Light?""",
        description="""Clear the dark cave in Eat at Joe's without using your punch""",
        points=10,
        badge="657009",
    ),
    573030: Achievement(
        id=573030,
        title="""Mangez Chez Joe""",
        description="""Break all 6 Electoon cages in Eat at Joe's""",
        points=5,
        badge="656670",
        type=AchievementType.PROGRESSION,
    ),
    573031: Achievement(
        id=573031,
        title="""Stalactites of Skops""",
        description="""Break all 6 Electoon cages in Mr. Skops' Stalactites""",
        points=5,
        badge="656671",
        type=AchievementType.PROGRESSION,
    ),
    578891: Achievement(
        id=578891,
        title="""Experienced Spelunker""",
        description="""Break all 6 Electoon cages in Mr. Skops' Stalactites in a single visit. Re-entering the level is allowed as long as you didn't break any cage""",
        points=5,
        badge="657010",
        type=AchievementType.MISSABLE,
    ),
    574647: Achievement(
        id=574647,
        title="""Tormented Scorpion""",
        description="""Defeat Mr. Skops in Mr. Skops' Stalactites""",
        points=10,
        badge="656684",
        type=AchievementType.PROGRESSION,
    ),
    577255: Achievement(
        id=577255,
        title="""SkopsGasm""",
        description="""Defeat Mr. Skops in Mr. Skops' Stalactites without taking damage""",
        points=10,
        badge="656702",
        type=AchievementType.MISSABLE,
    ),
    574661: Achievement(
        id=574661,
        title="""Castle of Delights""",
        description="""Free every Electoons and unlock Candy Chateau""",
        points=25,
        badge="656697",
        type=AchievementType.PROGRESSION,
    ),
    578892: Achievement(
        id=578892,
        title="""No Pressure""",
        description="""Clear Dark Rayman's chase without running longer than 1 second total""",
        points=10,
        badge="657011",
        type=AchievementType.MISSABLE,
    ),
    574648: Achievement(
        id=574648,
        title="""You've Saved the World!""",
        description="""Defeat Mr. Dark in Mr. Dark's Dare""",
        points=25,
        badge="656685",
        type=AchievementType.WIN_CONDITION,
    ),
    577256: Achievement(
        id=577256,
        title="""You're Doomed Rayman...""",
        description="""Defeat Mr. Dark in Mr. Dark's Dare without taking damage""",
        points=25,
        badge="656703",
        type=AchievementType.MISSABLE,
    ),
    578898: Achievement(
        id=578898,
        title="""No Time for Mr. Sax""",
        description="""Starting from a new save file, defeat Mr. Sax under 30:00 in a single session. 

Opt-in to the leaderboard by using the third save file""",
        points=50,
        badge="657017",
        type=AchievementType.MISSABLE,
    ),
})

leaderboards = OrderedDict({
    154961: Leaderboard(
        id=154961,
        title="""Speedrun - Sax%""",
        description="""Defeat Mr. Sax as fast as possible, starting from a new save. Use the 3rd save slot to opt-in""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152558: Leaderboard(
        id=152558,
        title="""Time Attack - Pink Plant Woods""",
        description="""Clear Pink Plant Woods as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152776: Leaderboard(
        id=152776,
        title="""Time Attack - Anguish Lagoon""",
        description="""Clear Anguish Lagoon as fast as possible before defeating Bzzit""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152777: Leaderboard(
        id=152777,
        title="""Time Attack - The Swamps of Forgetfulness""",
        description="""Clear The Swamps of Forgetfulness as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152778: Leaderboard(
        id=152778,
        title="""Time Attack - Moskito's Nest""",
        description="""Clear Moskito's Nest as fast as possible before defeating Moskito""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152779: Leaderboard(
        id=152779,
        title="""Time Attack - Bongo Hills""",
        description="""Clear Bongo Hills as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152780: Leaderboard(
        id=152780,
        title="""Time Attack - Allegro Presto""",
        description="""Clear Allegro Presto as fast as possible before defeating Mr. Sax""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152781: Leaderboard(
        id=152781,
        title="""Time Attack - Gong Heights""",
        description="""Clear Gong Heights as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152782: Leaderboard(
        id=152782,
        title="""Time Attack - Mr. Sax's Hullaballo""",
        description="""Clear Mr. Sax's Hullaballo as fast as possible before defeating Mr. Sax""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152783: Leaderboard(
        id=152783,
        title="""Time Attack - Twilight Gulch""",
        description="""Clear Twilight Gulch as fast as possible before defeating Mr. Stone""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152784: Leaderboard(
        id=152784,
        title="""Time Attack - The Hard Rocks""",
        description="""Clear The Hard Rocks as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152785: Leaderboard(
        id=152785,
        title="""Time Attack - Mr. Stone's Peaks""",
        description="""Clear Mr. Stone's Peaks as fast as possible before defeating Mr. Stone""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152786: Leaderboard(
        id=152786,
        title="""Time Attack - Eraser Plains""",
        description="""Clear Eraser Plains as fast as possible before defeating Pirate Mama""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152787: Leaderboard(
        id=152787,
        title="""Time Attack - Pencil Pentathlon""",
        description="""Clear Pencil Pentathlon as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152788: Leaderboard(
        id=152788,
        title="""Time Attack - Space Mama's Crater""",
        description="""Clear Space Mama's Crater as fast as possible before defeating Space Mama""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152789: Leaderboard(
        id=152789,
        title="""Time Attack - Crystal Palace""",
        description="""Clear Crystal Palace as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152790: Leaderboard(
        id=152790,
        title="""Time Attack - Eat at Joe's""",
        description="""Clear Eat at Joe's as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152791: Leaderboard(
        id=152791,
        title="""Time Attack - Mr. Skops' Stalactites""",
        description="""Clear Mr. Skops' Stalactites as fast as possible before defeating Mr. Skops""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152792: Leaderboard(
        id=152792,
        title="""Time Attack - Mr. Dark's Dare""",
        description="""Clear Mr. Dark's Dare as fast as possible before defeating Mr. Dark""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152793: Leaderboard(
        id=152793,
        title="""Magician Level - Pink Plant Woods 1""",
        description="""Clear the first Magician bonus level in Pink Plant Woods as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152794: Leaderboard(
        id=152794,
        title="""Magician Level - Pink Plant Woods 2""",
        description="""Clear the second Magician bonus level in Pink Plant Woods as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152795: Leaderboard(
        id=152795,
        title="""Magician Level - The Swamps of Forgetfulness""",
        description="""Clear the Magician bonus level in The Swamps of Forgetfulness as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152796: Leaderboard(
        id=152796,
        title="""Magician Level - Moskito's Nest""",
        description="""Clear the Magician bonus level in Moskito's Nest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152797: Leaderboard(
        id=152797,
        title="""Magician Level - Bongo Hills""",
        description="""Clear the Magician bonus level in Bongo Hills as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152798: Leaderboard(
        id=152798,
        title="""Magician Level - Allegro Presto""",
        description="""Clear the Magician bonus level in Allegro Presto as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152799: Leaderboard(
        id=152799,
        title="""Magician Level - The Hard Rocks""",
        description="""Clear the Magician bonus level in The Hard Rocks as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152800: Leaderboard(
        id=152800,
        title="""Magician Level - Mr. Stone's Peaks""",
        description="""Clear the Magician bonus level in Mr. Stone's Peaks as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152801: Leaderboard(
        id=152801,
        title="""Magician Level - Eraser Plains""",
        description="""Clear the Magician bonus level in Eraser Plains as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152802: Leaderboard(
        id=152802,
        title="""Magician Level - Space Mama's Crater""",
        description="""Clear the Magician bonus level in Space Mama's Crater as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    152803: Leaderboard(
        id=152803,
        title="""Magician Level - Crystal Palace""",
        description="""Clear the Magician bonus level in Crystal Palace as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
})