from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    573033: Achievement(
        id=573033,
        title="""Livingstone Grimace""",
        description="""Perform a grimace to scare a tall Livingstone""",
        points=1,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    574649: Achievement(
        id=574649,
        title="""Pink Plant Woods Magician 1""",
        description="""Clear the first Magician bonus level in Pink Plant Woods""",
        points=5,
        badge="00000",
    ),
    574636: Achievement(
        id=574636,
        title="""Punch Ability""",
        description="""Learn the punch ability""",
        points=1,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574650: Achievement(
        id=574650,
        title="""Pink Plant Woods Magician 2""",
        description="""Clear the second Magician bonus level in Pink Plant Woods""",
        points=5,
        badge="00000",
    ),
    574641: Achievement(
        id=574641,
        title="""Bzzit Boss""",
        description="""Defeat Bzzit in Anguish Lagoon""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574637: Achievement(
        id=574637,
        title="""Hang Ability""",
        description="""Learn the ability to hang onto platforms""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    573034: Achievement(
        id=573034,
        title="""Pink Plant Woods Challenge""",
        description="""Collect all 8 extra lives in Pink Plant Woods""",
        points=5,
        badge="00000",
    ),
    573015: Achievement(
        id=573015,
        title="""Pink Plant Woods Cages""",
        description="""Break all 6 Electoon cages in Pink Plant Woods""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    573016: Achievement(
        id=573016,
        title="""Anguish Lagoon Cages""",
        description="""Break all 6 Electoon cages in Anguish Lagoon""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574651: Achievement(
        id=574651,
        title="""The Swamps of Forgetfulness Magician""",
        description="""Clear the Magician bonus level in The Swamps of Forgetfulness""",
        points=5,
        badge="00000",
    ),
    573017: Achievement(
        id=573017,
        title="""The Swamps of Forgetfulness Cages""",
        description="""Break all 6 Electoon cages in The Swamps of Forgetfulness""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574652: Achievement(
        id=574652,
        title="""Moskito's Nest Magician""",
        description="""Clear the Magician bonus level in Moskito's Nest""",
        points=5,
        badge="00000",
    ),
    573499: Achievement(
        id=573499,
        title="""Tentacle flower""",
        description="""Defeat the tentacle flower in Moskito's Nest""",
        points=2,
        badge="00000",
    ),
    574642: Achievement(
        id=574642,
        title="""Moskito Boss""",
        description="""Defeat Moskito in Moskito's Nest""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574638: Achievement(
        id=574638,
        title="""Grappling Fist Ability""",
        description="""Learn the ability to grapple flying rings with your fist""",
        points=3,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    573018: Achievement(
        id=573018,
        title="""Moskito's Nest Cages""",
        description="""Break all 6 Electoon cages in Moskito's Nest""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574653: Achievement(
        id=574653,
        title="""Bongo Hills Magician""",
        description="""Clear the Magician bonus level in Bongo Hills""",
        points=5,
        badge="00000",
    ),
    573019: Achievement(
        id=573019,
        title="""Bongo Hills Cages""",
        description="""Break all 6 Electoon cages in Bongo Hills""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574654: Achievement(
        id=574654,
        title="""Allegro Presto Magician""",
        description="""Clear the Magician bonus level in Allegro Presto""",
        points=5,
        badge="00000",
    ),
    573020: Achievement(
        id=573020,
        title="""Allegro Presto Cages""",
        description="""Break all 6 Electoon cages in Allegro Presto""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574639: Achievement(
        id=574639,
        title="""Helicopter Ability""",
        description="""Learn the helicopter abillity""",
        points=4,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    1000001: Achievement(
        id=1000001,
        title="""Allegro Presto Challenge""",
        description="""Clear Allegro Presto under 4:30 before defeating Mr. Sax or having learned running""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    573021: Achievement(
        id=573021,
        title="""Gong Heights Cages""",
        description="""Break all 6 Electoon cages in Gong Heights""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    573022: Achievement(
        id=573022,
        title="""Mr. Sax's Hullaballoo Cages""",
        description="""Break all 6 Electoon cages in Mr. Sax's Hullaballoo""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574643: Achievement(
        id=574643,
        title="""Mr. Sax Boss""",
        description="""Defeat Mr. Sax in Mr. Sax's Hullaballoo""",
        points=10,
        badge="00000",
    ),
    573023: Achievement(
        id=573023,
        title="""Twilight Gulch Cages""",
        description="""Break all 6 Electoon cages in Twilight Gulch""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574655: Achievement(
        id=574655,
        title="""The Hard Rocks Magician""",
        description="""Clear the Magician bonus level in The Hard Rocks""",
        points=5,
        badge="00000",
    ),
    573024: Achievement(
        id=573024,
        title="""The Hard Rocks Cages""",
        description="""Break all 6 Electoon cages in The Hard Rocks""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574656: Achievement(
        id=574656,
        title="""Mr. Stone's Peaks Magician""",
        description="""Clear the Magician bonus level in Mr. Stone's Peaks""",
        points=5,
        badge="00000",
    ),
    573025: Achievement(
        id=573025,
        title="""Mr. Stone's Peaks Cages""",
        description="""Break all 6 Electoon cages in Mr. Stone's Peaks""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574644: Achievement(
        id=574644,
        title="""Mr. Stone Boss""",
        description="""Defeat Mr. Stone in Mr. Stone's Peaks""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574640: Achievement(
        id=574640,
        title="""Run Ability""",
        description="""Learn the running ability""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574657: Achievement(
        id=574657,
        title="""Eraser Plains Magician""",
        description="""Clear the Magician bonus level in Eraser Plains""",
        points=5,
        badge="00000",
    ),
    573026: Achievement(
        id=573026,
        title="""Eraser Plains Cages""",
        description="""Break all 6 Electoon cages in Eraser Plains""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574645: Achievement(
        id=574645,
        title="""Pirate Mama Boss""",
        description="""Defeat Pirate Mama in Eraser Plains""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    573027: Achievement(
        id=573027,
        title="""Pencil Pentathlon Cages""",
        description="""Break all 6 Electoon cages in Pencil Pentathlon""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574658: Achievement(
        id=574658,
        title="""Space Mama's Crater Magician""",
        description="""Clear the Magician bonus level in Space Mama's Crater""",
        points=5,
        badge="00000",
    ),
    573028: Achievement(
        id=573028,
        title="""Space Mama's Crater Cages""",
        description="""Break all 6 Electoon cages in Space Mama's Crater""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574646: Achievement(
        id=574646,
        title="""Space Mama Boss""",
        description="""Defeat Space Mama in Space Mama's Crater""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574659: Achievement(
        id=574659,
        title="""Crystal Palace Magician""",
        description="""Clear the Magician bonus level in Crystal Palace""",
        points=5,
        badge="00000",
    ),
    573029: Achievement(
        id=573029,
        title="""Crystal Palace Cages""",
        description="""Break all 6 Electoon cages in Crystal Palace""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    573030: Achievement(
        id=573030,
        title="""Eat at Joe's Cages""",
        description="""Break all 6 Electoon cages in Eat at Joe's""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    573031: Achievement(
        id=573031,
        title="""Mr. Skops' Stalactites Cages""",
        description="""Break all 6 Electoon cages in Mr. Skops' Stalactites""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574647: Achievement(
        id=574647,
        title="""Mr. Skops Boss""",
        description="""Defeat Mr. Skops in Mr. Skops' Stalactites""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574661: Achievement(
        id=574661,
        title="""All Cages""",
        description="""Free every Electoons and unlock Mr. Dark's Dare""",
        points=25,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    574648: Achievement(
        id=574648,
        title="""Mr. Dark Boss""",
        description="""Defeat Mr. Dark in Mr. Dark's Dare""",
        points=25,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    573032: Achievement(
        id=573032,
        title="""Extra Life""",
        description="""Obtain an extra life by collecting 100 Tings""",
        points=3,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    152558: Leaderboard(
        id=152558,
        title="""Time Attack - Pink Plant Woods""",
        description="""Clear Pink Plant Woods as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152776: Leaderboard(
        id=152776,
        title="""Time Attack - Anguish Lagoon""",
        description="""Clear Anguish Lagoon as fast as possible before defeating Bzzit""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152777: Leaderboard(
        id=152777,
        title="""Time Attack - The Swamps of Forgetfulness""",
        description="""Clear The Swamps of Forgetfulness as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152778: Leaderboard(
        id=152778,
        title="""Time Attack - Moskito's Nest""",
        description="""Clear Moskito's Nest as fast as possible before defeating Moskito""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152779: Leaderboard(
        id=152779,
        title="""Time Attack - Bongo Hills""",
        description="""Clear Bongo Hills as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152780: Leaderboard(
        id=152780,
        title="""Time Attack - Allegro Presto""",
        description="""Clear Allegro Presto as fast as possible before defeating Mr. Sax""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152781: Leaderboard(
        id=152781,
        title="""Time Attack - Gong Heights""",
        description="""Clear Gong Heights as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152782: Leaderboard(
        id=152782,
        title="""Time Attack - Mr. Sax's Hullaballoo""",
        description="""Clear Mr. Sax's Hullaballoo as fast as possible before defeating Mr. Sax""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152783: Leaderboard(
        id=152783,
        title="""Time Attack - Twilight Gulch""",
        description="""Clear Twilight Gulch as fast as possible before defeating Mr. Stone""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152784: Leaderboard(
        id=152784,
        title="""Time Attack - The Hard Rocks""",
        description="""Clear The Hard Rocks as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152785: Leaderboard(
        id=152785,
        title="""Time Attack - Mr. Stone's Peaks""",
        description="""Clear Mr. Stone's Peaks as fast as possible before defeating Mr. Stone""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152786: Leaderboard(
        id=152786,
        title="""Time Attack - Eraser Plains""",
        description="""Clear Eraser Plains as fast as possible before defeating Pirate Mama""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152787: Leaderboard(
        id=152787,
        title="""Time Attack - Pencil Pentathlon""",
        description="""Clear Pencil Pentathlon as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152788: Leaderboard(
        id=152788,
        title="""Time Attack - Space Mama's Crater""",
        description="""Clear Space Mama's Crater as fast as possible before defeating Space Mama""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152789: Leaderboard(
        id=152789,
        title="""Time Attack - Crystal Palace""",
        description="""Clear Crystal Palace as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152790: Leaderboard(
        id=152790,
        title="""Time Attack - Eat at Joe's""",
        description="""Clear Eat at Joe's as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152791: Leaderboard(
        id=152791,
        title="""Time Attack - Mr. Skops' Stalactites""",
        description="""Clear Mr. Skops' Stalactites as fast as possible before defeating Mr. Skops""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152792: Leaderboard(
        id=152792,
        title="""Time Attack - Mr. Dark's Dare""",
        description="""Clear Mr. Dark's Dare as fast as possible before defeating Mr. Dark""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152793: Leaderboard(
        id=152793,
        title="""Magician Level - Pink Plant Woods 1""",
        description="""Clear the first Magician bonus level in Pink Plant Woods as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152794: Leaderboard(
        id=152794,
        title="""Magician Level - Pink Plant Woods 2""",
        description="""Clear the second Magician bonus level in Pink Plant Woods as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152795: Leaderboard(
        id=152795,
        title="""Magician Level - The Swamps of Forgetfulness""",
        description="""Clear the Magician bonus level in The Swamps of Forgetfulness as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152796: Leaderboard(
        id=152796,
        title="""Magician Level - Moskito's Nest""",
        description="""Clear the Magician bonus level in Moskito's Nest as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152797: Leaderboard(
        id=152797,
        title="""Magician Level - Bongo Hills""",
        description="""Clear the Magician bonus level in Bongo Hills as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152798: Leaderboard(
        id=152798,
        title="""Magician Level - Allegro Presto""",
        description="""Clear the Magician bonus level in Allegro Presto as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152799: Leaderboard(
        id=152799,
        title="""Magician Level - The Hard Rocks""",
        description="""Clear the Magician bonus level in The Hard Rocks as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152800: Leaderboard(
        id=152800,
        title="""Magician Level - Mr. Stone's Peaks""",
        description="""Clear the Magician bonus level in Mr. Stone's Peaks as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152801: Leaderboard(
        id=152801,
        title="""Magician Level - Eraser Plains""",
        description="""Clear the Magician bonus level in Eraser Plains as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152802: Leaderboard(
        id=152802,
        title="""Magician Level - Space Mama's Crater""",
        description="""Clear the Magician bonus level in Space Mama's Crater as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    152803: Leaderboard(
        id=152803,
        title="""Magician Level - Crystal Palace""",
        description="""Clear the Magician bonus level in Crystal Palace as fast as possible""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
})
