from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    573015: Achievement(
        id=573015,
        title="""Pink Plant Woods Cages""",
        description="""Break all 6 Electoon cages in Pink Plant Woods""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573016: Achievement(
        id=573016,
        title="""Anguish Lagoon Cages""",
        description="""Break all 6 Electoon cages in Anguish Lagoon""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573017: Achievement(
        id=573017,
        title="""The Swamps of Forgetfulness Cages""",
        description="""Break all 6 Electoon cages in The Swamps of Forgetfulness""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573018: Achievement(
        id=573018,
        title="""Moskito's Nest Cages""",
        description="""Break all 6 Electoon cages in Moskito's Nest""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573019: Achievement(
        id=573019,
        title="""Bongo Hills Cages""",
        description="""Break all 6 Electoon cages in Bongo Hills""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573020: Achievement(
        id=573020,
        title="""Allegro Presto Cages""",
        description="""Break all 6 Electoon cages in Allegro Presto""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573021: Achievement(
        id=573021,
        title="""Gong Heights Cages""",
        description="""Break all 6 Electoon cages in Gong Heights""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573022: Achievement(
        id=573022,
        title="""Mr Sax's Hullaballo Cages""",
        description="""Break all 6 Electoon cages in Mr Sax's Hullaballo""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573023: Achievement(
        id=573023,
        title="""Twilight Gulch Cages""",
        description="""Break all 6 Electoon cages in Twilight Gulch""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573024: Achievement(
        id=573024,
        title="""The Hard Rocks Cages""",
        description="""Break all 6 Electoon cages in The Hard Rocks""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573025: Achievement(
        id=573025,
        title="""Mr Stone's Peaks Cages""",
        description="""Break all 6 Electoon cages in Mr Stone's Peaks""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573026: Achievement(
        id=573026,
        title="""Eraser Plains Cages""",
        description="""Break all 6 Electoon cages in Eraser Plains""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573027: Achievement(
        id=573027,
        title="""Pencil Pentathlon Cages""",
        description="""Break all 6 Electoon cages in Pencil Pentathlon""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573028: Achievement(
        id=573028,
        title="""Space Mama's Crater Cages""",
        description="""Break all 6 Electoon cages in Space Mama's Crater""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573029: Achievement(
        id=573029,
        title="""Crystal Palace Cages""",
        description="""Break all 6 Electoon cages in Crystal Palace""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573030: Achievement(
        id=573030,
        title="""Eat at Joe's Cages""",
        description="""Break all 6 Electoon cages in Eat at Joe's""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573031: Achievement(
        id=573031,
        title="""Mr Skops' Stalactites Cages""",
        description="""Break all 6 Electoon cages in Mr Skops' Stalactites""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    573032: Achievement(
        id=573032,
        title="""Extra Life""",
        description="""Obtain an extra life by collecting 100 Tings""",
        points=1,
    ),
    573033: Achievement(
        id=573033,
        title="""Livingstone Grimace""",
        description="""Perform a grimace to scare a tall Livingstone""",
        points=1,
        type=AchievementType.MISSABLE,
    ),
    573034: Achievement(
        id=573034,
        title="""Pink Plant Woods Challenge""",
        description="""Collect all 8 extra lives in Pink Plant Woods""",
        points=5,
    ),
    573499: Achievement(
        id=573499,
        title="""Tentacle flower""",
        description="""Defeat the tentacle flower in Moskito's Nest""",
        points=2,
    ),
    574636: Achievement(
        id=574636,
        title="""Punch Ability""",
        description="""Learn the punch ability""",
        points=1,
        type=AchievementType.PROGRESSION,
    ),
    574637: Achievement(
        id=574637,
        title="""Hang Ability""",
        description="""Learn the ability to hang onto platforms""",
        points=2,
        type=AchievementType.PROGRESSION,
    ),
    574638: Achievement(
        id=574638,
        title="""Grappling Fist Ability""",
        description="""Learn the ability to grapple flying rings with your fist""",
        points=3,
        type=AchievementType.PROGRESSION,
    ),
    574639: Achievement(
        id=574639,
        title="""Helicopter Ability""",
        description="""Learn the helicopter abillity""",
        points=4,
        type=AchievementType.PROGRESSION,
    ),
    574640: Achievement(
        id=574640,
        title="""Run Ability""",
        description="""Learn the running ability""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    574641: Achievement(
        id=574641,
        title="""Bzzit Boss""",
        description="""Defeat Bzzit in Anguish Lagoon""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    574642: Achievement(
        id=574642,
        title="""Moskito Boss""",
        description="""Defeat Moskito in Moskito's Nest""",
        points=10,
        type=AchievementType.PROGRESSION,
    ),
    574643: Achievement(
        id=574643,
        title="""Mr Sax Boss""",
        description="""Defeat Mr Sax in Mr Sax's Hullaballoo""",
        points=10,
        type=AchievementType.PROGRESSION,
    ),
    574644: Achievement(
        id=574644,
        title="""Mr Stone Boss""",
        description="""Defeat Mr Stone in Mr Stone's Peaks""",
        points=10,
        type=AchievementType.PROGRESSION,
    ),
    574645: Achievement(
        id=574645,
        title="""Pirate Mama Boss""",
        description="""Defeat Pirate Mama in Eraser Plains""",
        points=5,
        type=AchievementType.PROGRESSION,
    ),
    574646: Achievement(
        id=574646,
        title="""Space Mama Boss""",
        description="""Defeat Space Mama in Space Mama's Crater""",
        points=10,
        type=AchievementType.PROGRESSION,
    ),
    574647: Achievement(
        id=574647,
        title="""Mr Skops Boss""",
        description="""Defeat Mr Skops in Mr Skops' Stalactites""",
        points=10,
        type=AchievementType.PROGRESSION,
    ),
    574648: Achievement(
        id=574648,
        title="""Mr Dark Boss""",
        description="""Defeat Mr Dark in Mr Dark's Dare""",
        points=25,
        type=AchievementType.WIN_CONDITION,
    ),
    574649: Achievement(
        id=574649,
        title="""Pink Plant Woods Magician 1""",
        description="""Clear the first magician bonus level in Pink Plant Woods""",
        points=5,
    ),
    574650: Achievement(
        id=574650,
        title="""Pink Plant Woods Magician 2""",
        description="""Clear the second magician bonus level in Pink Plant Woods""",
        points=5,
    ),
    574651: Achievement(
        id=574651,
        title="""The Swamps of Forgetfulness Magician""",
        description="""Clear the magician bonus level in The Swamps of Forgetfulness""",
        points=5,
    ),
    574652: Achievement(
        id=574652,
        title="""Moskito's Nest Magician""",
        description="""Clear the magician bonus level in Moskito's Nest""",
        points=5,
    ),
    574653: Achievement(
        id=574653,
        title="""Bongo Hills Magician""",
        description="""Clear the magician bonus level in Bongo Hills""",
        points=5,
    ),
    574654: Achievement(
        id=574654,
        title="""Allegro Presto Magician""",
        description="""Clear the magician bonus level in Allegro Presto""",
        points=5,
    ),
    574655: Achievement(
        id=574655,
        title="""The Hard Rocks Magician""",
        description="""Clear the magician bonus level in The Hard Rocks""",
        points=5,
    ),
    574656: Achievement(
        id=574656,
        title="""Mr Stone's Peaks Magician""",
        description="""Clear the magician bonus level in Mr Stone's Peaks""",
        points=5,
    ),
    574657: Achievement(
        id=574657,
        title="""Eraser Plains Magician""",
        description="""Clear the magician bonus level in Eraser Plains""",
        points=5,
    ),
    574658: Achievement(
        id=574658,
        title="""Space Mama's Crater Magician""",
        description="""Clear the magician bonus level in Space Mama's Crater""",
        points=5,
    ),
    574659: Achievement(
        id=574659,
        title="""Crystal Palace Magician""",
        description="""Clear the magician bonus level in Crystal Palace""",
        points=5,
    ),
    574661: Achievement(
        id=574661,
        title="""All Cages""",
        description="""Free every Electoons and unlock Mr Dark's Dare""",
        points=25,
        type=AchievementType.PROGRESSION,
    ),
})

leaderboards = OrderedDict({
    152558: Leaderboard(
        "Pink Plant Woods - Time Attack",
        "",
        id=152558,
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True
    )
})
