from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    634108: Achievement(
        id=634108,
        title="""Tutorial""",
        description="""Defeat Bowser during the tutorial in Hard Mode. The Challenge Medal must stay equipped during every subsequent boss battle""",
        points=1,
        badge="00000",
    ),
    635253: Achievement(
        id=635253,
        title="""Broque Monsieur""",
        description="""Defeat Broque Monsieur in Hard Mode [Level <= 5]""",
        points=5,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635254: Achievement(
        id=635254,
        title="""Sea Pipe Statue""",
        description="""Defeat the Sea Pipe Statue in Hard Mode [Level <= 6]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635255: Achievement(
        id=635255,
        title="""Scutlet""",
        description="""Defeat Scutlet in Hard Mode [M&L Level <= 6]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635256: Achievement(
        id=635256,
        title="""Broggy""",
        description="""Defeat Broggy in Hard Mode [Bowser Level <= 7]""",
        points=5,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635257: Achievement(
        id=635257,
        title="""Wiggler""",
        description="""Defeat Wiggler in Hard Mode [Level <= 10]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635258: Achievement(
        id=635258,
        title="""Durmite""",
        description="""Defeat Durmite in Hard Mode [M&L Level <= 8]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635270: Achievement(
        id=635270,
        title="""Gauntlet Class 1""",
        description="""Complete the Challenge Gauntlet Class 1 in Hard Mode [M&L Level <= 18]""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635259: Achievement(
        id=635259,
        title="""Midbus""",
        description="""Defeat Midbus inside Fawful Theater in Hard Mode [Bowser Level <= 15]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635260: Achievement(
        id=635260,
        title="""Alpha Keratin""",
        description="""Defeat Alpha Keratin in Hard Mode without using Badges [M&L Level <= 12]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635271: Achievement(
        id=635271,
        title="""Gauntlet Class 2""",
        description="""Complete the Challenge Gauntlet Class 2 in Hard Mode [M&L Level <= 21]""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635261: Achievement(
        id=635261,
        title="""Bowser""",
        description="""Defeat Bowser inside the Toadley Clinic in Hard Mode without using Badges [M&L Level <= 16]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635262: Achievement(
        id=635262,
        title="""Wisdurm""",
        description="""Defeat Wisdurm in Hard Mode without using Badges [M&L Level <= 20]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635272: Achievement(
        id=635272,
        title="""Gauntlet Class 3""",
        description="""Complete the Challenge Gauntlet Class 3 in Hard Mode [M&L Level <= 26]""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635263: Achievement(
        id=635263,
        title="""Bowser Memory M & L""",
        description="""Defeat Bowser Memory M & L in Hard Mode without using Badges [M&L Level <= 21]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635273: Achievement(
        id=635273,
        title="""Gauntlet Class 4""",
        description="""Complete the Challenge Gauntlet Class 4 in Hard Mode [M&L Level <= 29]""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635264: Achievement(
        id=635264,
        title="""Shroobs""",
        description="""Defeat the Shroobs inside the Preservation Chamber in Bowser's Castle in Hard Mode without using Badges [M&L Level <= 25]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635265: Achievement(
        id=635265,
        title="""Junker""",
        description="""Defeat Junker in Hard Mode without using Badges [M&L Level <= 26]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635274: Achievement(
        id=635274,
        title="""Gauntlet Class 5""",
        description="""Complete the Challenge Gauntlet Class 5 in Hard Mode [M&L Level <= 34]""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635266: Achievement(
        id=635266,
        title="""Blizzard Midbus""",
        description="""Defeat Blizzard Midbus in Hard Mode without using Badges [Level <= 28]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635267: Achievement(
        id=635267,
        title="""Dark Star""",
        description="""Defeat the Dark Star in Hard Mode without using Badges [M&L Level <= 30]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635275: Achievement(
        id=635275,
        title="""Gauntlet Class 6""",
        description="""Complete the Challenge Gauntlet Class 6 in Hard Mode [M&L Level <= 40]""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635268: Achievement(
        id=635268,
        title="""Dark Fawful""",
        description="""Defeat Dark Fawful in Hard Mode without using Badges [Level <= 33]""",
        points=10,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635269: Achievement(
        id=635269,
        title="""Final Boss""",
        description="""Defeat Dark Bowser and the Dark Star Core in Hard Mode without using Badges [Level <= 35]""",
        points=25,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    635276: Achievement(
        id=635276,
        title="""Gauntlet Class 7""",
        description="""Complete the Challenge Gauntlet Class 7 in Hard Mode [M&L Level <= 50]""",
        points=50,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
})

leaderboards = OrderedDict({
    171999: Leaderboard(
        id=171999,
        title="""Lowest Level - Monsieur Broque""",
        description="""Defeat Monsieur Broque in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172000: Leaderboard(
        id=172000,
        title="""Lowest Level - Sea Pipe Statue""",
        description="""Defeat the Sea Pipe Statue in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172001: Leaderboard(
        id=172001,
        title="""Lowest Level - Scutlet""",
        description="""Defeat Scutlet in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172002: Leaderboard(
        id=172002,
        title="""Lowest Level - Broggy""",
        description="""Defeat Broggy in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172003: Leaderboard(
        id=172003,
        title="""Lowest Level - Wiggler""",
        description="""Defeat Wiggler in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172004: Leaderboard(
        id=172004,
        title="""Lowest Level - Durmite""",
        description="""Defeat Durmite in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172005: Leaderboard(
        id=172005,
        title="""Lowest Level - Midbus""",
        description="""Defeat Midbus inside Fawful Theater in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172006: Leaderboard(
        id=172006,
        title="""Lowest Level - Alpha Keratin""",
        description="""Defeat Alpha Keratin in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172007: Leaderboard(
        id=172007,
        title="""Lowest Level - Bowser""",
        description="""Defeat Bowser inside the Toadley Clinic in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172008: Leaderboard(
        id=172008,
        title="""Lowest Level - Wisdurm""",
        description="""Defeat Wisdurm in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172009: Leaderboard(
        id=172009,
        title="""Lowest Level - Bowser Memory M & L""",
        description="""Defeat Bowser Memory M & L in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172010: Leaderboard(
        id=172010,
        title="""Lowest Level - Shroobs""",
        description="""Defeat the Shroobs inside the Preservation Chamber in Bowser's Castle in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172011: Leaderboard(
        id=172011,
        title="""Lowest Level - Junker""",
        description="""Defeat Junker in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172012: Leaderboard(
        id=172012,
        title="""Lowest Level - Blizzard Midbus""",
        description="""Defeat Blizzard Midbus in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172013: Leaderboard(
        id=172013,
        title="""Lowest Level - Dark Star""",
        description="""Defeat the Dark Star in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172014: Leaderboard(
        id=172014,
        title="""Lowest Level - Dark Fawful""",
        description="""Defeat Dark Fawful in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172015: Leaderboard(
        id=172015,
        title="""Lowest Level - Final Boss""",
        description="""Defeat Dark Bowser and the Dark Star Core in Hard Mode with the lowest combined Mario, Luigi and Bowser level without using badges""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172016: Leaderboard(
        id=172016,
        title="""Lowest Level - Challenge Gauntlet Class 1""",
        description="""Complete the Challenge Gauntlet Class 1 in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172017: Leaderboard(
        id=172017,
        title="""Lowest Level - Challenge Gauntlet Class 2""",
        description="""Complete the Challenge Gauntlet Class 2 in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172018: Leaderboard(
        id=172018,
        title="""Lowest Level - Challenge Gauntlet Class 3""",
        description="""Complete the Challenge Gauntlet Class 3 in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172019: Leaderboard(
        id=172019,
        title="""Lowest Level - Challenge Gauntlet Class 4""",
        description="""Complete the Challenge Gauntlet Class 1 in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=True,
    ),
    172020: Leaderboard(
        id=172020,
        title="""Lowest Level - Challenge Gauntlet Class 5""",
        description="""Complete the Challenge Gauntlet Class 5 in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=False,
    ),
    172021: Leaderboard(
        id=172021,
        title="""Lowest Level - Challenge Gauntlet Class 6""",
        description="""Complete the Challenge Gauntlet Class 6 in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=False,
    ),
    172022: Leaderboard(
        id=172022,
        title="""Lowest Level - Challenge Gauntlet Class 7""",
        description="""Complete the Challenge Gauntlet Class 7 in Hard Mode with the lowest combined Mario, Luigi and Bowser level""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=False,
    ),
})