from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    642019: Achievement(
        id=642019,
        title="""tutorial""",
        description="""Complete the Tutorial missions""",
        points=5,
        badge="00000",
    ),
    642020: Achievement(
        id=642020,
        title="""prog_construction""",
        description="""Complete the Construction story chapter""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    642021: Achievement(
        id=642021,
        title="""prog_camelot""",
        description="""Complete the Camelot story chapter""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    642022: Achievement(
        id=642022,
        title="""prog_wild_west""",
        description="""Complete the Wild West story chapter""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    642023: Achievement(
        id=642023,
        title="""prog_arabian""",
        description="""Complete the Arabian story chapter""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    642024: Achievement(
        id=642024,
        title="""prog_prehistoric""",
        description="""Complete the Prehistoric story chapter""",
        points=25,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    642025: Achievement(
        id=642025,
        title="""unlocks_sounds""",
        description="""Buy every Sound Banks from the shop""",
        points=5,
        badge="00000",
    ),
    642026: Achievement(
        id=642026,
        title="""unlocks_maps""",
        description="""Buy every Maps from the shop""",
        points=5,
        badge="00000",
    ),
    642027: Achievement(
        id=642027,
        title="""unlocks_hats""",
        description="""Buy every Worm Hats from the shop""",
        points=5,
        badge="00000",
    ),
    642028: Achievement(
        id=642028,
        title="""unlocks_face""",
        description="""Buy every Worm Spectacles from the shop""",
        points=5,
        badge="00000",
    ),
    642029: Achievement(
        id=642029,
        title="""unlocks_hands""",
        description="""Buy every Worm Hands from the shop""",
        points=5,
        badge="00000",
    ),
    642030: Achievement(
        id=642030,
        title="""unlocks_mustaches""",
        description="""Buy every Worm Mustaches from the shop""",
        points=5,
        badge="00000",
    ),
    642031: Achievement(
        id=642031,
        title="""unlocks_weapons""",
        description="""Buy every Weapons from the shop""",
        points=5,
        badge="00000",
    ),
    642032: Achievement(
        id=642032,
        title="""unlocks_game_styles""",
        description="""Buy every Game Styles from the shop""",
        points=5,
        badge="00000",
    ),
    642033: Achievement(
        id=642033,
        title="""unlocks_sets""",
        description="""Buy every Character Sets from the shop""",
        points=25,
        badge="00000",
    ),
    642034: Achievement(
        id=642034,
        title="""Wholesome Coins Are Worth Half a Coin""",
        description="""Obtain a reward from spinning 3 identical reels on the Wormpot""",
        points=5,
        badge="00000",
    ),
    642135: Achievement(
        id=642135,
        title="""Bronze Damage""",
        description="""Deal over 25,000 damage points""",
        points=2,
        badge="00000",
    ),
    642136: Achievement(
        id=642136,
        title="""Silver Damage""",
        description="""Deal over 50,000 damage points""",
        points=5,
        badge="00000",
    ),
    642137: Achievement(
        id=642137,
        title="""Gold Damage""",
        description="""Deal over 100,000 damage points""",
        points=10,
        badge="00000",
    ),
    642138: Achievement(
        id=642138,
        title="""Body Count""",
        description="""Kill over 500 worms""",
        points=5,
        badge="00000",
    ),
    642139: Achievement(
        id=642139,
        title="""3 Bagger""",
        description="""Kill 3 worms in a single turn""",
        points=3,
        badge="00000",
    ),
    642140: Achievement(
        id=642140,
        title="""4 Bagger""",
        description="""Kill 4 worms in a single turn""",
        points=4,
        badge="00000",
    ),
    642141: Achievement(
        id=642141,
        title="""Barrel Buster""",
        description="""Destroy 500 poison barrels""",
        points=5,
        badge="00000",
    ),
    642142: Achievement(
        id=642142,
        title="""Hot Foot""",
        description="""Trigger 500 land mines""",
        points=5,
        badge="00000",
    ),
    642143: Achievement(
        id=642143,
        title="""Big Blast""",
        description="""Cause 500 damage points in a single turn""",
        points=5,
        badge="00000",
    ),
    642144: Achievement(
        id=642144,
        title="""Rocketeer""",
        description="""Consume 2,000 units of Jet Pack fuel""",
        points=5,
        badge="00000",
    ),
    642145: Achievement(
        id=642145,
        title="""Animal Lover""",
        description="""Kill 200 worms with animal weaponry""",
        points=5,
        badge="00000",
    ),
    642146: Achievement(
        id=642146,
        title="""Magic Bullet""",
        description="""Kill 3 worms within two blasts of the Shotgun""",
        points=3,
        badge="00000",
    ),
    642147: Achievement(
        id=642147,
        title="""Greedy Worm""",
        description="""Collect over 500 crates""",
        points=5,
        badge="00000",
    ),
    642148: Achievement(
        id=642148,
        title="""Weapon Specialist""",
        description="""Cause over 8,000 damage points with the Bazooka""",
        points=5,
        badge="00000",
    ),
    642149: Achievement(
        id=642149,
        title="""The Beast Within""",
        description="""Kill 3 worms with one animal weapon in a single turn""",
        points=3,
        badge="00000",
    ),
    642150: Achievement(
        id=642150,
        title="""Take Pride in Your Achievements""",
        description="""Obtain all 15 trophies""",
        points=25,
        badge="00000",
    ),
    642889: Achievement(
        id=642889,
        title="""time_bonus_construction""",
        description="""Obtain the time bonus on all missions of the Construction story chapter""",
        points=10,
        badge="00000",
    ),
    642890: Achievement(
        id=642890,
        title="""time_bonus_camelot""",
        description="""Obtain the time bonus on all missions of the Camelot story chapter""",
        points=10,
        badge="00000",
    ),
    642891: Achievement(
        id=642891,
        title="""time_bonus_wild_west""",
        description="""Obtain the time bonus on all missions of the Wild West story chapter""",
        points=10,
        badge="00000",
    ),
    642892: Achievement(
        id=642892,
        title="""time_bonus_arabian""",
        description="""Obtain the time bonus on all missions of the Arabian story chapter""",
        points=10,
        badge="00000",
    ),
    642893: Achievement(
        id=642893,
        title="""time_bonus_prehistoric""",
        description="""Obtain the time bonus on all missions of the Prehistoric story chapter""",
        points=10,
        badge="00000",
    ),
    642894: Achievement(
        id=642894,
        title="""easter_egg_1""",
        description="""Discover the "88 MPH" Easter Egg""",
        points=3,
        badge="00000",
    ),
    642895: Achievement(
        id=642895,
        title="""easter_egg_2""",
        description="""Discover the "Hidden Room" Easter Egg""",
        points=3,
        badge="00000",
    ),
    642896: Achievement(
        id=642896,
        title="""easter_egg_3""",
        description="""Discover the "Shoot the Crapper" Easter Egg""",
        points=3,
        badge="00000",
    ),
    642897: Achievement(
        id=642897,
        title="""easter_egg_4""",
        description="""Discover the "Hidden Crate" Easter Egg""",
        points=3,
        badge="00000",
    ),
    642898: Achievement(
        id=642898,
        title="""easter_egg_5""",
        description="""Discover the "Feed the T. Rex" Easter Egg""",
        points=3,
        badge="00000",
    ),
    642899: Achievement(
        id=642899,
        title="""challenge_completion""",
        description="""Complete all 8 non-deathmatch challenges""",
        points=10,
        badge="00000",
    ),
    642900: Achievement(
        id=642900,
        title="""challenge_time_bonus""",
        description="""Beat the Team17's times on all 8 non-deathmatch challenges""",
        points=10,
        badge="00000",
    ),
    642901: Achievement(
        id=642901,
        title="""deathmatch_completion""",
        description="""Complete all 10 deathmatch challenges""",
        points=10,
        badge="00000",
    ),
    642902: Achievement(
        id=642902,
        title="""deathmatch_time_bonus""",
        description="""Beat the Team17's times on all 10 deathmatch challenges""",
        points=25,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    174176: Leaderboard(
        id=174176,
        title="""Warning: Achievements Unsupported""",
        description="""Your emulator might be unsupported, please contact the set developper with a save state attached to your message""",
        format=LeaderboardFormat.VALUE,
        lower_is_better=False,
    ),
})