from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    631472: Achievement(
        id=631472,
        title="""Return of the Fire Hero""",
        description="""Defeat Hibito during your first match in the King's Area""",
        points=1,
        badge="00000",
        type=AchievementType.MISSABLE,
    ),
    631473: Achievement(
        id=631473,
        title="""Grand Prix: First Round""",
        description="""Win the 1st round of G-1 Major Grand Prix in the Elekick Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631474: Achievement(
        id=631474,
        title="""Grand Prix: Second Round""",
        description="""Win the 2nd round of G-1 Major Grand Prix in the Volcano Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631475: Achievement(
        id=631475,
        title="""Grand Prix: Third Round""",
        description="""Win the 3rd round of G-1 Major Grand Prix in the Harmonic Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631476: Achievement(
        id=631476,
        title="""Grand Prix: Fourth Round""",
        description="""Win the 4th round of G-1 Major Grand Prix in the Water Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631477: Achievement(
        id=631477,
        title="""Money Can't Buy Everything""",
        description="""Win the Okuman G Grand Prix""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631478: Achievement(
        id=631478,
        title="""Grand Prix: Fifth Round""",
        description="""Win the 5th round of G-1 Major Grand Prix in the Canyon Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631479: Achievement(
        id=631479,
        title="""Grand Prix: Sixth Round""",
        description="""Win the 6th round of G-1 Major Grand Prix in the Harmonic Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631480: Achievement(
        id=631480,
        title="""Grand Prix: Seventh Round""",
        description="""Win the 7th round of G-1 Major Grand Prix in the Water Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631481: Achievement(
        id=631481,
        title="""Grand Prix: Eighth Round""",
        description="""Win the 8th round of G-1 Major Grand Prix in the Elekick Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631482: Achievement(
        id=631482,
        title="""Grand Prix: Quarterfinals""",
        description="""Win the quarterfinals of G-1 Major Grand Prix in the Canyon Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631483: Achievement(
        id=631483,
        title="""Grand Prix: Semifinals""",
        description="""Win the semifinals of G-1 Major Grand Prix in the Volcano Area""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631484: Achievement(
        id=631484,
        title="""Fall of the King""",
        description="""Defeat King in the Underground Lab""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631491: Achievement(
        id=631491,
        title="""Superhero""",
        description="""Defeat the Evil One and witness the end of the main story""",
        points=25,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    631485: Achievement(
        id=631485,
        title="""G-Quester""",
        description="""Complete all 5 story side quests in the G-Center""",
        points=5,
        badge="00000",
    ),
    631486: Achievement(
        id=631486,
        title="""Victory Lap""",
        description="""Complete all 13 story revisit quests in the G-Center""",
        points=10,
        badge="00000",
    ),
    631487: Achievement(
        id=631487,
        title="""Mysterious Grappers""",
        description="""Complete all 3 secret grapper quests in the G-Center""",
        points=5,
        badge="00000",
    ),
    631488: Achievement(
        id=631488,
        title="""Gorilla Attack""",
        description="""Complete all 4 Goril quests in the G-Center""",
        points=5,
        badge="00000",
    ),
    631489: Achievement(
        id=631489,
        title="""Full Metal Armor""",
        description="""Complete all 4 Arman quests in the G-Center""",
        points=5,
        badge="00000",
    ),
    631490: Achievement(
        id=631490,
        title="""Survivor""",
        description="""Complete the Sudden Death quest in the G-Center""",
        points=5,
        badge="00000",
    ),
    631518: Achievement(
        id=631518,
        title="""Treasure Hunter""",
        description="""Open all 56 unique chests in the game""",
        points=25,
        badge="00000",
    ),
    631519: Achievement(
        id=631519,
        title="""Bulleteer""",
        description="""Collect all 97 story bullets""",
        points=50,
        badge="00000",
    ),
    631492: Achievement(
        id=631492,
        title="""Super Rich""",
        description="""Possess over 150,000 credits""",
        points=10,
        badge="00000",
    ),
    631493: Achievement(
        id=631493,
        title="""Super Celebrity""",
        description="""Buy every bullet at the Okuman Land""",
        points=5,
        badge="00000",
    ),
    631494: Achievement(
        id=631494,
        title="""Scorer""",
        description="""Buy every Beat Scores""",
        points=5,
        badge="00000",
    ),
    631495: Achievement(
        id=631495,
        title="""Composer""",
        description="""Compose 20 Beat Scores""",
        points=1,
        badge="00000",
    ),
    631496: Achievement(
        id=631496,
        title="""Attacker""",
        description="""Land 500 basic attacks""",
        points=1,
        badge="00000",
    ),
    631497: Achievement(
        id=631497,
        title="""Rushman""",
        description="""Land 100 combo attacks""",
        points=1,
        badge="00000",
    ),
    631498: Achievement(
        id=631498,
        title="""Though Guy""",
        description="""Endure 1,000 hits""",
        points=1,
        badge="00000",
    ),
    631499: Achievement(
        id=631499,
        title="""Berserker""",
        description="""Deal over 1,000 total damage""",
        points=1,
        badge="00000",
    ),
    631513: Achievement(
        id=631513,
        title="""Variant Hunter""",
        description="""Defeat 200 variants""",
        points=5,
        badge="00000",
    ),
    631500: Achievement(
        id=631500,
        title="""Matter Breaker""",
        description="""Defeat 200 grappers""",
        points=5,
        badge="00000",
    ),
    631514: Achievement(
        id=631514,
        title="""G-Liver""",
        description="""Grap in every G-Live arena""",
        points=5,
        badge="00000",
    ),
    631515: Achievement(
        id=631515,
        title="""Iron Man""",
        description="""Win 10 matches without taking damage""",
        points=10,
        badge="00000",
    ),
    631501: Achievement(
        id=631501,
        title="""Gladiator""",
        description="""Win 10 matches with 100 MP or less remaining""",
        points=10,
        badge="00000",
    ),
    631516: Achievement(
        id=631516,
        title="""Special Ranker""",
        description="""Win 20 matches with over 1,000 credits awarded""",
        points=10,
        badge="00000",
    ),
    631517: Achievement(
        id=631517,
        title="""Beat Drive Winner""",
        description="""Win a match with every grapper in VS CPU mode after performing a Beat Drive""",
        points=10,
        badge="00000",
    ),
    631503: Achievement(
        id=631503,
        title="""Super Beat Combo Winner""",
        description="""Win a match with every grapper in VS CPU mode after performing a Super Beat Combo""",
        points=10,
        badge="00000",
    ),
    631502: Achievement(
        id=631502,
        title="""Beat Drive Mania""",
        description="""Activate Beat Drive 50 times""",
        points=5,
        badge="00000",
    ),
    631504: Achievement(
        id=631504,
        title="""Beat Combo Mania""",
        description="""Earn the titles for performing 100 Beat Combos, 100 Full Beat Combos and 50 Super Beat Combos""",
        points=5,
        badge="00000",
    ),
    631505: Achievement(
        id=631505,
        title="""Charismatic Grapper""",
        description="""Earn the titles for winning 50, 100 and 200 matches""",
        points=25,
        badge="00000",
    ),
    631520: Achievement(
        id=631520,
        title="""G-Live Master""",
        description="""Earn the titles for battling in G-Live 20, 50 and 200 times""",
        points=10,
        badge="00000",
    ),
    631521: Achievement(
        id=631521,
        title="""Primary Elementalist""",
        description="""Earn the titles for using Fire, Aqua, Lightning and Earth bullets 200 times each in battle""",
        points=5,
        badge="00000",
    ),
    631522: Achievement(
        id=631522,
        title="""Secondary Elementalist""",
        description="""Earn the titles for using Wind, Ice, Flower and Poison bullets 200 times each in battle""",
        points=5,
        badge="00000",
    ),
    631506: Achievement(
        id=631506,
        title="""Tertiary Elementalist""",
        description="""Earn the titles for using Light, Dark, Music and Void bullets 200 times each in battle""",
        points=5,
        badge="00000",
    ),
    631523: Achievement(
        id=631523,
        title="""CoroCoro Challenger""",
        description="""Complete the Survival 10 challenge at the Challenge Arena. Press [Up R Down Left Start] sequentially in the title screen to unlock the Challenge Arena""",
        points=10,
        badge="00000",
    ),
    631524: Achievement(
        id=631524,
        title="""Dashing Prospect""",
        description="""Complete the My Treasure quest in less than 1 minute 30 seconds""",
        points=5,
        badge="00000",
    ),
    631507: Achievement(
        id=631507,
        title="""The Floor is Darkness""",
        description="""Complete the Underground Lab Core in less than 2 minutes without stepping on floor hazards""",
        points=5,
        badge="00000",
    ),
    631525: Achievement(
        id=631525,
        title="""1 Man vs. 1 Gorilla""",
        description="""Complete the Final Goril quest without equipping any bullet""",
        points=5,
        badge="00000",
    ),
    631508: Achievement(
        id=631508,
        title="""Ultimate Trashcan""",
        description="""Complete the Ultimate Arman quest without equipping any bullet""",
        points=5,
        badge="00000",
    ),
    631526: Achievement(
        id=631526,
        title="""Grease Fire Don't Mix With Water""",
        description="""On VS CPU mode, defeat Kyle while playing as Hibito in the Water G-Hall with only Fire bullets equipped and traps ON""",
        points=3,
        badge="00000",
    ),
    631527: Achievement(
        id=631527,
        title="""Let's Get This Arena Humid""",
        description="""On VS CPU mode, defeat Daichi while playing as Kyle in the Canyon G-Hall with only Water bullets equipped and traps ON""",
        points=3,
        badge="00000",
    ),
    631509: Achievement(
        id=631509,
        title="""Man vs. Earth""",
        description="""On VS CPU mode, defeat Guy while playing as Daichi in the Elekick G-Hall with only Earth bullets equipped and traps ON""",
        points=3,
        badge="00000",
    ),
    631528: Achievement(
        id=631528,
        title="""Can a Gangster Leave The Gang?""",
        description="""On VS CPU mode, defeat Jet while playing as Guy in the G-Live G-Hall with only Lightning bullets equipped""",
        points=3,
        badge="00000",
    ),
    631531: Achievement(
        id=631531,
        title="""Nothing Personal Kid""",
        description="""On VS CPU mode, defeat Hibito while playing as Kamzou in the Volcano G-Hall with only Flower bullets equipped and traps ON""",
        points=3,
        badge="00000",
    ),
    631529: Achievement(
        id=631529,
        title="""Take a Hint""",
        description="""On VS CPU mode, defeat Kamzou while playing as Neon in the Canyon G-Hall with only Music bullets equipped and traps ON""",
        points=3,
        badge="00000",
    ),
    631510: Achievement(
        id=631510,
        title="""Sound Clout""",
        description="""On VS CPU mode, defeat Neon while playing as Jet in the Harmonic G-Hall with only Void bullets equipped""",
        points=3,
        badge="00000",
    ),
    631511: Achievement(
        id=631511,
        title="""Train For Another Hundred Years""",
        description="""On VS CPU mode, defeat Raio while playing as Cross in the King's G-Hall with only Light bullets equipped""",
        points=3,
        badge="00000",
    ),
    631530: Achievement(
        id=631530,
        title="""Faster Than Light""",
        description="""On VS CPU mode, defeat Cross while playing as Zeke in the G-Live G-Hall with only Dark bullets equipped""",
        points=3,
        badge="00000",
    ),
    631512: Achievement(
        id=631512,
        title="""Deja Vu""",
        description="""On VS CPU mode, defeat Zeke while playing as Raio in the Okuman G-Hall without any bullet equipped""",
        points=3,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    169497: Leaderboard(
        id=169497,
        title="""Time Trial - Mirage Egg""",
        description="""Complete the "Mirage Egg" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169487: Leaderboard(
        id=169487,
        title="""Time Trial - Return It""",
        description="""Complete the "Return It" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169498: Leaderboard(
        id=169498,
        title="""Time Trial - DS Dropped""",
        description="""Complete the "DS Dropped" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169499: Leaderboard(
        id=169499,
        title="""Time Trial - DoraDora""",
        description="""Complete the "DoraDora" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169488: Leaderboard(
        id=169488,
        title="""Time Trial - My Treasure""",
        description="""Complete the "My Treasure" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169500: Leaderboard(
        id=169500,
        title="""Time Trial - Goshi Desert""",
        description="""Complete the "Goshi Desert" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169501: Leaderboard(
        id=169501,
        title="""Time Trial - Saru Ruins""",
        description="""Complete the "Saru Ruins" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169489: Leaderboard(
        id=169489,
        title="""Time Trial - Zoff Pass""",
        description="""Complete the "Zoff Pass" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169502: Leaderboard(
        id=169502,
        title="""Time Trial - Ghost Underground""",
        description="""Complete the "Ghost Underground" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169490: Leaderboard(
        id=169490,
        title="""Time Trial - Kenmeri""",
        description="""Complete the "Kenmeri" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169508: Leaderboard(
        id=169508,
        title="""Time Trial - Poshka Ruins""",
        description="""Complete the "Poshka Ruins" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169503: Leaderboard(
        id=169503,
        title="""Time Trial - Win Desert""",
        description="""Complete the "Win Desert" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169491: Leaderboard(
        id=169491,
        title="""Time Trial - Iwaku Pass""",
        description="""Complete the "Iwaku Pass" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169509: Leaderboard(
        id=169509,
        title="""Time Trial - Hidden Path""",
        description="""Complete the "Hidden Path" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169510: Leaderboard(
        id=169510,
        title="""Time Trial - Underground Lab""",
        description="""Complete the "Underground Lab" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169492: Leaderboard(
        id=169492,
        title="""Time Trial - Underground Lab Core""",
        description="""Complete the "Underground Lab Core" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169782: Leaderboard(
        id=169782,
        title="""Time Trial - Matter Invert""",
        description="""Complete the "Matter Invert" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169504: Leaderboard(
        id=169504,
        title="""Time Trial - Other Space""",
        description="""Complete the "Other Space" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169511: Leaderboard(
        id=169511,
        title="""Time Trial - Change Beat!""",
        description="""Complete the "Change Beat!" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169493: Leaderboard(
        id=169493,
        title="""Time Trial - Char Grapper""",
        description="""Complete the "Char Grapper" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169512: Leaderboard(
        id=169512,
        title="""Time Trial - Myst Grapper""",
        description="""Complete the "Myst Grapper" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169505: Leaderboard(
        id=169505,
        title="""Time Trial - Goril's Roar""",
        description="""Complete the "Goril's Roar" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169494: Leaderboard(
        id=169494,
        title="""Time Trial - Goril's Roar+""",
        description="""Complete the "Goril's Roar+" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169513: Leaderboard(
        id=169513,
        title="""Time Trial - Goril's Rage""",
        description="""Complete the "Goril's Rage" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169495: Leaderboard(
        id=169495,
        title="""Time Trial - Final Goril""",
        description="""Complete the "Final Goril" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169506: Leaderboard(
        id=169506,
        title="""Time Trial - Arman Ranger""",
        description="""Complete the "Arman Ranger" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169514: Leaderboard(
        id=169514,
        title="""Time Trial - Arman Soldier""",
        description="""Complete the "Arman Soldier" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169496: Leaderboard(
        id=169496,
        title="""Time Trial - Golden Arman""",
        description="""Complete the "Golden Arman" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169515: Leaderboard(
        id=169515,
        title="""Time Trial - Ultimate Arman""",
        description="""Complete the "Ultimate Arman" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169507: Leaderboard(
        id=169507,
        title="""Time Trial - Sudden Death""",
        description="""Complete the "Sudden Death" quest as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169783: Leaderboard(
        id=169783,
        title="""Time Trial - Challenge Arena""",
        description="""Complete the Survival 10 challenge at the Challenge Arena as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
})